
//**********************************************************
// ´úÂë±à¼­Æ÷
//**********************************************************

// MyShell.h : main header file for the MYSHELL application
//

#if !defined(AFX_MYSHELL_H__6EA9071B_5253_44C1_829C_96DE5076E8D2__INCLUDED_)
#define AFX_MYSHELL_H__6EA9071B_5253_44C1_829C_96DE5076E8D2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#ifndef __AFXWIN_H__
#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"		// main symbols
#include "../NdSound/NDSound.h"
#include "GameDataSet.h"

#define WM_MY_MESSAGE (WM_USER+100)
enum { DLG_LOGIN = 0, DLG_ROLECHOOSE, DLG_ROLECREATE,
       DLG_MAIN, DLG_QUERY, DLG_FRIEND, DLG_GROUP, DLG_TASKLIST, DLG_TASKGET, DLG_TASKVIEW,
       DLG_QUERY_ROLE, DLG_CONTACT, DLG_KNIGHTAGE_REGROUP, DLG_KNIGHTAGE_MANAGER , DLG_KNIGHTAGEDOC, DLG_KNIGHTAGERENAME,
       DLG_QUERY_MISSION, DLG_QUERY_SKILL, DLG_QUERY_WEAPON,
       DLG_NPCBUY, DLG_MPCGOODS, DLG_TRADE, DLG_TRADENPC, DLG_TRADEMPC, DLG_DEPOT,
       DLG_SKILL, DLG_SETUP, DLG_ACT, DLG_MAGIC, DLG_IMPROVE, DLG_NPCFACE, DLG_EMBED, DLG_HOTKEY,
       DLG_INSHELP, DLG_MSGSEND, DLG_MSGRECEIVE, DLG_MPCBOOTH, DLG_NPCBOOTH, DLG_CHAT,
       DLG_BLACK, DLG_LEVWORD,
       DLG_EFFIGY, DLG_LAY, DLG_OTHER, DLG_NPCEQUIP, DLG_XP, DLG_ENEMY, DLG_ENMSTATE, DLG_TALKACT,
       DLG_EQUIP, DLG_REALSKILL, DLG_IDENTIFY, DLG_EMBLEMBUY,
       DLG_TBOARDLIST, DLG_TBOARDINFO, DLG_TBOARDUP,
       DLG_ALL, DLG_MONSTEREGG, DLG_TASKUPITEM, DLG_MONSTER,
       DLG_STONEGOODS0, DLG_STONEGOODS1, DLG_MONSTERSKILL,
       DLG_MONSTERHATCH, DLG_MONSTERDEPOT, DLG_MONSTERIMPROVE, DLG_MONSTERNPC, DLG_MONSTEREVOLVE,
       DLG_AUCPACKAGE, DLG_AUCTION, DLG_ADDAUCITEM, DLG_CHATLOG, DLG_EMOTION
     };

enum {CHAT_TARGET_PLAYER = 100, CHAT_TARGET_FRIEND};

enum {ON_EXIT = 0, ON_EXIT_LOGIN, ON_MIN, ON_LOGIN_NEW, ON_BACK_PLAY, ON_CLOSE_MDLG,
      ON_ROLECHOOSE_RETURN, ON_ROLECHOOSE_CHOOSE,
      ON_ROLECREATE_CREATE, ON_TALK_CLOSE,
      ON_MSGDLG_GOODS, ON_MSGDLG_HIDE, ON_MSGDLG_POINT, ON_MSGDLG_STATIC, ON_MSGDLG_IMAGE, ON_MSGDLG_TEST, ON_MSGDLG_FACE,
      ON_ICON_PICKUP, ON_ICON_DROP, ON_ICON_TRADE, ON_ICON_USE, ON_ICON_BUY, ON_ICON_QUSE, ON_ICON_ID, ON_ICON_PNT,
      ON_NPCBUY_CLOSE, ON_NPCBUY_FIX, ON_MPCGOODS_CLOSE, ON_MPCGOODS_MONEYDROP,
      ON_MAIN_TRADE, ON_TRADE_ACCEPT, ON_TRADE_CLOSE, ON_MAIN_SCREENMOVE,
      ON_TALK_DEL, ON_TALK_LOG, ON_TALK_LOGCLOSE, ON_TALK_SETUP, ON_IMPROVE_CLOSE, ON_NPCFACE_CLOSE,
      ON_GROUP_SETUP, ON_GROUP_JOIN, ON_GROUP_INVITE, ON_TEAMJOIN_ACCEPT, ON_TEAMINVITE_ACCEPT, ON_TEAM_DISMISS, ON_TEAMDISMISS_ACCEPT,
      ON_FRIENDDEL_ACCEPT, ON_FRIENDADD_ACCEPT, ON_TALKDEL_ACCEPT, ON_FACTIONSUB_ACCEPT, ON_FACTION_BACK,
      ON_FACTION_REGROUP, ON_FACTION_KICK, ON_FACTION_SUB, ON_FACTION_INVITE, ON_FACTION_JOIN, ON_FACTION_OUT, ON_FACTIONDOC_OPEN, ON_FACTION_RENAME,
      ON_FACTION_MANAGER,	ON_FACTIONINVITE_ACCEPT, ON_FACTIONJOIN_ACCEPT, ON_MONEYDROP_ACCEPT, ON_FACTIONOUT_ACCEPT,	ON_FACTIONDEL_ACCEPT,
      ON_HELPDLG_SHOW, ON_FRIEND_ADD, ON_FRIEND_CHAT, ON_FRIEND_LEAVE, ON_FRDSTATE_DEL, ON_FRIEND_RESUME,
      ON_SETUP_MODECHANGE, ON_SETUP_HOTKEY, ON_SETUP_OTHER,
      ON_MAGIC_CHOOSE, ON_XP_CHOOSE, ON_MONSTER_CHOOSE, ON_MONSTER_OPTION,
      ON_OWNER_MOVE, ON_OWNER_STOP, ON_EMBED_CLOSE, ON_EFFIGY_CLOSE, ON_MSGSEND_VIEW, ON_MSGREC_REVERT, ON_MSGREC_CLOSE,
      ON_MPCBOOTH_CLOSE, ON_MPCBOOTH_ADDITEM, ON_BOOTHOPEN_ACCEPT, ON_MPCBOOTHADD_ACCEPT, ON_MPCBOOTH_HIDE,
      ON_MPCBOOTH_CHANGE, ON_MPCBOOTHCHG_ACCEPT, ON_MPCBOOTH_HAWK,
      ON_NPCBOOTH_CLOSE, ON_CHAT_SIFT, ON_LAY_CLOSE, ON_MPCCOURT_ACCEPT,
      ON_TASKITEM_UP, ON_TASKUP_CLOSE, ON_TASKVIEW_OPEN, ON_TASKVIEW_CLOSE, ON_TASKVIEW_BACK, ON_TASKUP_OK, ON_TASKSET_OK,
      ON_OTHER_DELNPC, ON_MAIN_NPCEQUIP, ON_IMPTITEM_ACCEPT, ON_DROPITEM_ACCEPT,
      ON_TACKOFF_ACCEPT, ON_EMBED_TACKOFF, ON_SETUP_SHIFT, ON_MAIN_EXPDOWN,
      ON_JOINDICE_ACCEPT, ON_OUTDICE_ACCEPT, ON_DICE_LIST, ON_ENMSTATE_DEL, ON_ENEMYDEL_ACCEPT, ON_FRDSTATE_SHOW, ON_DICE_HIDE,
      ON_BLACK_CLOSE, ON_INTERFACE_CHANGE, ON_INSHELP_SHOW, ON_RESOURCE_ACCEPT, ON_TALKACT_SHOW, ON_LEVWORD_CHAT, ON_EXIT_ACCEPT, ON_EXIT_REFUSE,
      ON_EMPTY_MSG, ON_MSG_HIDE, ON_MSG_WARNING, ON_ROLECREATE_ACCEPT, ON_ROLECREATE_REFUSE, ON_SPLITITEM_ACCEPT,
      ON_HEAD_LEVUP, ON_RSIDEDLG_OPEN, ON_RSIDEDLG_CLOSE , ON_CLICK_CHATSET,
      ON_MIPMAP_OPEN, ON_BIGMAP_OPEN, ON_ANNOUNCEINFO_OPEN, ON_TEAMMAGIC_OPEN, ON_TEAMMAGIC_SEL,
      ON_TEACHER_REQUEST, ON_STUDENT_REQUEST, ON_TEACHER_ACCEPT, ON_STUDENT_ACCEPT,
      ON_MONSTER_HATCH, ON_MONSTER_DEPOT, ON_MONSTER_IMP, ON_MONSTER_ALIVE, DEL_LISTITEM, ON_MONSTERHEAD_SET,
      ON_MONSTER_DROP, ON_MONSTERDROP_ACCEPT, ON_CHECKOUTEGG_ACCEPT,
      ON_FACTION_ADDALLY, ON_FACTION_DELALLY, ON_FACTION_ADDENEMY,
      ON_FACTION_DELENEMY, ON_FACTION_ADDALLYOK, ON_FACTION_ADDENEMYOK, ON_DLGTASK_CLOSE,
      ON_DLGEMOTION_OPEN, ON_DLGEMOTION_CLOSE, ON_EMOTION_INSERT, ON_PACKBTN_MOVE, ON_MONSTER_CALL, ON_MONSTER_KILL,
     };

extern char	g_strControlAni[32] ;
extern char g_strMagicAni[32] ;
extern BOOL	g_bPickUp ;
extern CBrush g_StockBrush;
extern BOOL	g_bMouseMoveIn ;
const char g_strItemAni[]			   = _T( "ani/ItemMinIcon.Ani" ) ;
const char g_strSetupIni[]			   = _T( "ini/GameSetup.Ini" ) ;

const int GRID_ICON_WIDTH		= 42 ;
const int GRID_ICON_HEIGHT		= 42 ;
const int GRID_ICONMOVE_WIDTH	= 50 ;
const int GRID_ICONMOVE_HEIGHT	= 50 ;
const int GRID_ICONQUICK_WIDTH  = 32 ;
const int GRID_ICONQUICK_HEIGHT = 32 ;
const int GRID_ICONQUICK_NUM	= 10 ;
const int DLG_FRAME_AMOUNT		= 20 ;
const int DLG_MAIN_HEIGHT		= 141 ;

struct GemInfo
{
    BYTE	btWeaponSkill ;
    BYTE	btMagicExp ;
    BYTE	btRoleExp ;
    BYTE	btAmount ;
    BYTE	btAtk ;
    BYTE	btMagicAtk ;
    BYTE	btHit ;
    OBJID	strID ;
} ;
/////////////////////////////////////////////////////////////////////////////
// CMyShellApp:
// See MyShell.cpp for the implementation of this class
//
class CMyShellApp : public CWinApp
{
public:
    static const char* StringChange ( const char* strText, BYTE btType = 0 );
    CMyShellApp();
    //	static GemInfo m_GemInfo[21] ;

    // Overrides
    // ClassWizard generated virtual function overrides
    //{{AFX_VIRTUAL(CMyShellApp)
public:
    virtual BOOL InitInstance();
    virtual BOOL OnIdle(LONG lCount);
    virtual int ExitInstance();
    //}}AFX_VIRTUAL

    // Implementation

    //{{AFX_MSG(CMyShellApp)
    // NOTE - the ClassWizard will add and remove member functions here.
    //    DO NOT EDIT what you see in these blocks of generated code !
    //}}AFX_MSG
    DECLARE_MESSAGE_MAP()
};


/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MYSHELL_H__6EA9071B_5253_44C1_829C_96DE5076E8D2__INCLUDED_)
