//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MyShell.rc 使用
//
#define IDB_TITLEBARBK                  2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MYSHELL_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOGIN                129
#define IDD_MAIN_DIALOG                 130
#define IDD_DIALOG_QUERY                131
#define IDD_DIALOG_QUERY_ROLE           132
#define IDD_DIALOG_QUERY_FACTION        133
#define IDD_DIALOG_CONTACT              133
#define IDD_DIALOG_QUERY_WEAPON         134
#define IDD_DIALOG_QUERY_MISSION        135
#define IDD_DIALOG_SKILL                136
#define IDD_DIALOG_GOODS                137
#define IDD_DIALOG_TRADE                137
#define IDD_DIALOG_SETUP                138
#define IDD_DIALOG_CHAT                 139
#define IDD_DIALOG_ACT                  140
#define IDD_DIALOG_GROUP                141
#define IDC_CURSOR_POINT                144
#define IDD_DIALOG_TALK                 145
#define IDC_CURSOR_HAND                 146
#define IDC_CURSOR_FIX                  146
#define IDD_DIALOG_LISTBOX              148
#define IDD_DIALOG_SERVER               149
#define IDD_DIALOG_ROLECHOOSE           150
#define IDD_DIALOG_ROLECREATE           151
#define IDD_DIALOG_NPCBUY               152
#define IDD_DIALOG_MPCGOODS             153
#define IDB_TALKBK                      155
#define IDB_DLGSETUP                    156
#define IDD_DIALOG_CONFIRM              158
#define IDB_SETUPBK                     159
#define IDD_DIALOG_FRIEND               160
#define IDD_DIALOG_DEPOT                161
#define IDD_DIALOG_QUERY_SKILL          163
#define IDD_DIALOG_TASK                 173
#define IDD_MENU_TALK                   174
#define IDC_CURSOR_PK                   184
#define IDC_CURSOR_H                    185
#define IDD_DIALOG1                     187
#define IDD_DIALOG_MAGIC                188
#define IDD_DIALOG_XP                   189
#define IDD_DIALOG_PK                   191
#define IDD_DIALOG_TITLEBAR             195
#define IDD_DIALOG_FRDSTATE             209
#define IDD_DIALOG_IMPROVE              211
#define IDD_DIALOG_NPCFACE              212
#define IDD_DIALOG_KONGFU               214
#define IDD_DIALOG_HELP                 215
#define IDB_HELPBK                      216
#define IDD_DIALOG_LOG                  218
#define IDB_LOGBK                       224
#define IDB_LOGDEL                      226
#define IDB_LOGDELALL                   227
#define IDB_CLOSE                       228
#define IDD_DIALOG_EMBED                229
#define IDB_HELPMORE                    230
#define IDD_DIALOG_HOTKEY               231
#define IDD_DIALOG_MSGSEND              232
#define IDD_DIALOG_MPCBOOTH             233
#define IDD_DIALOG_NPCBOOTH             234
#define IDD_DIALOG_HAWK                 235
#define IDD_DIALOG_MSGRECEIVE           238
#define IDD_DIALOG_BLACK                239
#define IDD_DIALOG_LEVWORD              240
#define IDD_DIALOG_EFFIGY               241
#define IDD_DIALOG_LAY                  242
#define IDC_CURSOR_TEAMIN               245
#define IDC_CURSOR_TEAMJOIN             247
#define IDC_CURSOR_TEAMINVITE           248
#define IDC_CURSOR_FACOUT               249
#define IDC_CURSOR_FRDADD               250
#define IDC_CURSOR_MARRY                251
#define IDC_CURSOR_FACIN                252
#define IDC_CURSOR_TRADE                253
#define IDD_DIALOG_OTHER                255
#define IDC_CURSOR_DELNPC               256
#define IDD_DIALOG_FACSTATE             257
#define IDD_DIALOG_NPCEQUIP             258
#define IDC_CURSOR_NPCEQUIP             259
#define IDD_DIALOG_DICE                 262
#define IDC_CURSOR_CHIP10000            263
#define IDC_CURSOR_CHIP1000             264
#define IDC_CURSOR_CHIP100              265
#define IDD_DIALOG_DICELIST             267
#define IDD_MENU_GROUP                  268
#define IDD_DIALOG_ENEMY                269
#define IDD_DIALOG_ENMSTATE             270
#define IDD_DIALOG_PROINTRO             271
#define IDD_DIALOG_INSHELP              272
#define IDD_DIALOG_LOGO                 273
#define IDD_DIALOG_TALKACT              274
#define IDD_DIALOG_EXP                  275
#define IDD_DIALOG_QUERY_TITLE          276
#define IDD_DIALOG_HEAD                 277
#define IDD_DIALOG_MIPMAP               278
#define IDD_DIALOG_EQUIP                279
#define IDD_DIALOG_MSG                  280
#define IDD_DIALOG_IDENTIFY             284
#define IDD_DIALOG_PROGRESS             285
#define IDD_DIALOG_CONTACT_KNIGHTAGE    287
#define IDD_DIALOG_CONTACT_KNIGHTAGE_BASIC 288
#define IDD_DIALOG_CONTACT_KNIGHTAGE_SUB 289
#define IDD_DIALOG_CONTACT_KNIGHTAGE_CONNECT 290
#define IDD_DIALOG_CONTACT_KNIGHTAGE_MEMBER 291
#define IDD_DIALOG_CONTACT_KNIGHTAGE_ARMY 292
#define IDD_DIALOG_CONTACT_KNIGHTAGE_FUNCTION 293
#define IDD_DIALOG_CONTACT_TEACHER      294
#define IDD_DIALOG_CONTACT_FRIEND       295
#define IDD_DIALOG_EMBLEMBUY            296
#define IDD_DIALOG_PROSS                297
#define IDD_DIALOG_HP                   298
#define IDD_DIALOG_MONSTER              299
#define IDD_DIALOG_QGOOD                300
#define IDD_DIALOG_STONEGOODS           301
#define IDD_DIALOG_SETUP_GRAPH          302
#define IDD_DIALOG_SETUP_CHAT           303
#define IDD_DIALOG_SETUP_HOTKEY         304
#define IDD_DIALOG_SETUP_MUSIC          305
#define IDD_DIALOG_FACTION              306
#define IDD_DIALOG_KNIGHTAGE            307
#define IDD_DIALOG_KNIGHTAGE_BASE       308
#define IDD_DIALOG_KNIGHTAGE_MEMBER     309
#define IDD_DIALOG_KNIGHTAGE_ENEMY      310
#define IDD_DIALOG_KNIGHTAGE_RESOURCE   311
#define IDD_DIALOG_KNIGHTAGE_LEVWORD    312
#define IDD_DIALOG_KNIGHTAGE_BILLBOARD  313
#define IDD_DIALOG_KNIGHTAGE_STATE      314
#define IDD_DIALOG_KNIGHTAGE_WORDLOOK   316
#define IDD_DIALOG_KNIGHTAGE_WORDSEND   317
#define IDD_DIALOG_KNIGHTAGE_SELDOEDIT  318
#define IDD_DIALOG_KNIGHTAGE_REGROUP    319
#define IDD_DIALOG_KNIGHTAGE_RENAME     321
#define IDD_DIALOG_KNIGHTAGE_MANAGER    321
#define IDD_DIALOG_SKILL_HOTKEYS        324
#define IDD_DIALOG_BIGMAP               325
#define IDD_DIALOG_NORMSG               326
#define IDD_DIALOG_PLAYERTASKVIEW       327
#define IDD_DIALOG_PLAYERTASKLIST       328
#define IDD_DIALOG_PLAYERTASKGET        329
#define IDD_DIALOG_TASKKILLER           330
#define IDD_DIALOG_TASKITEM             331
#define IDD_DIALOG_TASKMONSTER          332
#define IDD_DIALOG_UPTASKITEM           334
#define IDD_DIALOG_TEACHERBOARD         335
#define IDD_DIALOG_TBOARDLIST           337
#define IDD_DIALOG_TBOARDDETIAL         338
#define IDD_DIALOG_SCHOOLLIST           339
#define IDD_DIALOG_MONSTERHATCH         340
#define IDD_DIALOG_MONSTERIMPROVE       341
#define IDD_DIALOG_MONSTERDEPOT         342
#define IDD_DIALOG_MONSTERNPC           343
#define IDD_DIALOG_TXTACTION            344
#define IDD_DIALOG_TALKTARGET           345
#define IDD_DIALOG_BIDAUCTION           346
#define IDD_DIALOG_AUCPACKAGE           349
#define IDD_DIALOG_ADDAUCITEM           350
#define IDC_CURSOR_POINTDOWN            353
#define IDD_DIALOG_KNIGHTAGE_DOC        354
#define IDD_DIALOG_KNIGHTAGE_ORDAIN     357
#define IDD_DIALOG_KNIGHTAGE_GROUPRENAME 358
#define IDD_DIALOG_CHATROOMLOGIN        359
#define IDD_DIALOG_CHATROOMLIST         360
#define IDD_DIALOG_CHATROOMMAG          361
#define IDD_DIALOG_MONSTERSKILL         362
#define IDD_DIALOG_MONSTERHEADS         363
#define IDD_MENU_PETATK                 364
#define IDD_DIALOG_EMOTION              365
#define IDD_DIALOG_MONSTEREVOLVE        366
#define IDD_DIALOG_ROOMLG               368
#define IDC_STCBG                       1000
#define IDC_LOGIN_BTN_NEW               1001
#define IDC_LOGIN_BTN_NET               1002
#define IDC_MAIN_HP                     1003
#define IDC_LOGIN_EDT_ACCOUNT           1003
#define IDC_MAIN_MP                     1004
#define IDC_LOGIN_EDT_PASSWORD          1004
#define IDC_MAIN_QUERY                  1005
#define IDC_LOGIN_BTN_ADD               1005
#define IDC_LOGIN_EDT_ACCOUNT2          1005
#define IDC_MAIN_SKILL                  1006
#define IDC_MAIN_QUERY4                 1006
#define IDC_MAIN_STONES                 1006
#define IDC_MAIN_GOOD                   1007
#define IDC_MAIN_SETUP                  1008
#define IDC_EXP_CLOSE                   1008
#define IDC_MAIN_ACT                    1009
#define IDC_MAIN_MONSTER                1009
#define IDC_MAIN_CHAT                   1010
#define IDC_MAIN_GROUP                  1011
#define IDC_MAIN_RUN                    1012
#define IDC_MAIN_PK                     1013
#define IDC_MAIN_TALK                   1014
#define IDC_MAIN_MAP                    1015
#define IDC_MAIN_STAND                  1016
#define IDC_MAIN_QUERY2                 1016
#define IDC_MAIN_NPCEQUIP               1016
#define IDC_MAIN_WEAPON                 1017
#define IDC_CHK_RUN                     1017
#define IDC_MAIN_POWER                  1018
#define IDC_MAIN_XP                     1018
#define IDC_MAIN_EXP                    1019
#define IDC_MAIN_HEAVY                  1020
#define IDC_CHK_EQUIP                   1020
#define IDC_MAIN_GOODBOX                1021
#define IDC_MAIN_SKILLBOX               1022
#define IDC_MAIN_MAGIC                  1022
#define IDC_QUERY_ROLE                  1023
#define IDC_MAIN_SCREENMOVE             1023
#define IDC_MAGIC_IMG2                  1023
#define IDC_QUERY_FACTION               1024
#define IDC_MAGIC_IMG3                  1024
#define IDC_MAIN_FACTION                1024
#define IDC_QUERY_WEAPON                1025
#define IDC_MAGIC_IMG7                  1025
#define IDC_MAIN_FORCE                  1025
#define IDC_QUERY_MISSION               1026
#define IDC_MAGIC_IMG4                  1026
#define IDC_MAIN_FRIEND                 1026
#define IDC_QUERY_CLOSE                 1027
#define IDC_MAGIC_IMG5                  1027
#define IDC_MAIN_QUERY3                 1027
#define IDC_CHK_PK                      1027
#define IDC_STATIC1                     1028
#define IDC_DEPOT_BTN_GET               1028
#define IDC_QUERY_SKILL                 1028
#define IDC_PK_GROUP                    1028
#define IDC_MAGIC_IMG8                  1028
#define IDC_CHK_EXP                     1028
#define IDC_STATIC2                     1029
#define IDC_PK_SAFE                     1029
#define IDC_QUERY_CLOSEB                1029
#define IDC_MAGIC_IMG9                  1029
#define IDC_QUERY_TITLE                 1029
#define IDC_CHK_HEAD                    1029
#define IDC_STATIC3                     1030
#define IDC_MAGIC_IMG10                 1030
#define IDC_PK_ARRESTMENT               1030
#define IDC_CHK_MAP                     1030
#define IDC_BTN_UP_HIDE                 1030
#define IDC_STATIC4                     1031
#define IDC_BTN_LEFT_HIDE               1031
#define IDC_STATIC5                     1032
#define IDC_STATIC6                     1033
#define IDC_STATIC7                     1034
#define IDC_STATIC9                     1035
#define IDC_STATIC10                    1036
#define IDC_STATIC11                    1037
#define IDC_STATIC12                    1038
#define IDC_STATIC22                    1038
#define IDC_STATIC8                     1039
#define IDC_STATIC33                    1039
#define IDC_STATIC13                    1040
#define IDC_STATIC44                    1040
#define IDC_ROLE_PIC_HEAD               1041
#define IDC_STATIC55                    1041
#define IDC_FACTION_LST_DATA            1042
#define IDC_STATIC66                    1042
#define IDC_FACTION_BTN_OUT             1043
#define IDC_WEAPON_LST_DATA             1044
#define IDC_FACTION_BTN_SUB             1044
#define IDC_FACTION_BTN_INVITE          1045
#define IDC_WEAPON_BTN_ARM              1046
#define IDC_WEAPON_BTN_S                1046
#define IDC_FACTION_BTN_JOIN            1046
#define IDC_WEAPON_BTN_ARMOR            1047
#define IDC_WEAPON_BTN_D                1047
#define IDC_FACTION_BTN_WORD            1047
#define IDC_MISSION_BTN_REP             1048
#define IDC_WEAPON_BTN_O                1048
#define IDC_FACTION_BTN_FRIEND          1048
#define IDC_SKILL_BTN_1                 1049
#define IDC_WEAPON_IMA1                 1049
#define IDC_FACTION_BTN_ENEMY           1049
#define IDC_SKILL_IMG_1                 1049
#define IDC_SKILL_BTN_2                 1050
#define IDC_WEAPON_IMA2                 1050
#define IDC_SKILL_IMG_2                 1050
#define IDC_SKILL_BTN_3                 1051
#define IDC_WEAPON_IMA3                 1051
#define IDC_SKILL_IMG_3                 1051
#define IDC_SKILL_BTN_4                 1052
#define IDC_WEAPON_IMA4                 1052
#define IDC_FACTION_BTN_STATE           1052
#define IDC_SKILL_IMG_4                 1052
#define IDC_SKILL_BTN_5                 1053
#define IDC_WEAPON_IMA5                 1053
#define IDC_SKILL_IMG_5                 1053
#define IDC_SKILL_BTN_6                 1054
#define IDC_WEAPON_IMA6                 1054
#define IDC_SKILL_IMG_11                1054
#define IDC_SKILLKEY_IMG1               1054
#define IDC_SKILL_BTN_7                 1055
#define IDC_WEAPON_IMA7                 1055
#define IDC_SKILL_IMG_22                1055
#define IDC_SKILLKEY_IMG2               1055
#define IDC_SKILL_BTN_8                 1056
#define IDC_WEAPON_IMA8                 1056
#define IDC_SKILL_IMG_33                1056
#define IDC_SKILLKEY_IMG3               1056
#define IDC_SKILL_BTN_CLOSE             1057
#define IDC_WEAPON_IMA11                1057
#define IDC_SKILLKEY_IMG4               1057
#define IDC_GOODS_IMG_HEAD              1058
#define IDC_SKILL_BTN_UP                1058
#define IDC_WEAPON_IMA22                1058
#define IDC_GOODS_IMG_GARNISH           1059
#define IDC_SKILL_BTN_DOWN              1059
#define IDC_WEAPON_IMA33                1059
#define IDC_GOODS_IMG_LHAND             1060
#define IDC_WEAPON_IMA44                1060
#define IDC_SKILL_IMG_44                1060
#define IDC_SKILLKEY_IMG5               1060
#define IDC_GOODS_IMG_CLOTH             1061
#define IDC_WEAPON_IMA55                1061
#define IDC_SKILL_IMG_55                1061
#define IDC_SKILLKEY_IMG6               1061
#define IDC_GOODS_IMG_RHAND             1062
#define IDC_WEAPON_IMA66                1062
#define IDC_SKILL_BTN_PRO               1062
#define IDC_GOODS_IMG_SASH              1063
#define IDC_WEAPON_IMA77                1063
#define IDC_WEAPON_BTN_UP               1063
#define IDC_SKILL_BTN_LIFE              1063
#define IDC_GOODS_IMG_SHOE              1064
#define IDC_WEAPON_IMA88                1064
#define IDC_WEAPON_BTN_DOWN             1064
#define IDC_SKILL_BTN_OTHER             1064
#define IDC_GOODS_GRI_GOODS             1065
#define IDC_SKILL_IMG_6                 1065
#define IDC_GOODS_BTN_CLOSE             1066
#define IDC_SKILL_IMG_66                1066
#define IDC_GOODS_PIC_BODY              1067
#define IDC_SKILL_IMG_7                 1067
#define IDC_GOODS_STA_DATA              1068
#define IDC_SKILL_IMG_77                1068
#define IDC_SETUP_BTN_EXIT              1070
#define IDC_SETUP_BTN_CLOSE             1071
#define IDC_SETUP_BTN_RETURN            1071
#define IDC_SETUP_BTN_REAL              1072
#define IDC_SETUP_BTN_RELOGIN           1072
#define IDC_SETUP_SLI_MUSIC             1073
#define IDC_SETUP_SLI_EFFECT            1074
#define IDC_SETUP_SLI_MASS              1075
#define IDC_SETUP_BTN_SHADOWCLOSE       1075
#define IDC_SETUP_BTN_WIN               1076
#define IDC_CHAT_LST_INDEX1             1077
#define IDC_SETUP_BTN_SIMPLE            1077
#define IDC_SETUP_BTN_FULL              1078
#define IDC_CHAT_LST_INDEX2             1078
#define IDC_CHAT_BTN_OK                 1079
#define IDC_SETUP_BTN_WINB              1079
#define IDC_CHAT_BTN_CLOSE              1080
#define IDC_SETUP_BTN_FULLB             1080
#define IDC_CHAT_STA_DATA               1081
#define IDC_SETUP_BTN_HOTKEY            1081
#define IDC_ACT_BTN1                    1082
#define IDC_SETUP_BTN_OTHER             1082
#define IDC_ACT_BTN2                    1083
#define IDC_GROUP_BTN_CREATE            1083
#define IDC_GROUP_BTN_1                 1083
#define IDC_SETUP_CHK_NAMEOPEN          1083
#define IDC_ACT_BTN3                    1084
#define IDC_GROUP_BTN_JOIN              1084
#define IDC_GROUP_BTN_2                 1084
#define IDC_SETUP_BTN_MODE              1084
#define IDC_ACT_BTN4                    1085
#define IDC_GROUP_BTN_CLOSE             1085
#define IDC_SETUP_BTN_LEFT              1085
#define IDC_ACT_BTN5                    1086
#define IDC_GROUP_LST_ID                1086
#define IDC_GROUP_IMG1                  1086
#define IDC_SETUP_BTN_RIGHT             1086
#define IDC_ACT_BTN6                    1087
#define IDC_GROUP_IMG2                  1087
#define IDC_SETUP_BTN_GRAPH             1087
#define IDC_ACT_BTN7                    1088
#define IDC_GROUP_IMG3                  1088
#define IDC_SETUP_BTN_MUSIC             1088
#define IDC_ACT_BTN8                    1089
#define IDC_TALK_COB_DATA               1089
#define IDC_TALK_EDT_DATA               1089
#define IDC_GROUP_IMG4                  1089
#define IDC_GROUP_IMG5                  1090
#define IDC_ACT_BTN9                    1090
#define IDC_TALK_BTN_SEND               1091
#define IDC_GROUP_BTN_INVITE            1091
#define IDC_ACT_BTN10                   1091
#define IDC_GROUP_CHK_3                 1091
#define IDC_TALK_BTN_CLEAR              1092
#define IDC_GROUP_BTN_OUT               1092
#define IDC_GROUP_BTN_4                 1092
#define IDC_TALK_BTN_SEND2              1092
#define IDC_TALK_CHK_PK                 1092
#define IDC_EDIT1                       1093
#define IDC_DEPOT_EDT_MONEY             1093
#define IDC_GROUP_BTN_UNLAY             1093
#define IDC_TASK_EDT_ANSWER             1093
#define IDC_TALK_EDT_NAME               1093
#define IDC_LOG_DATA                    1093
#define IDC_MSGSEND_DATA                1093
#define IDC_HAWK_EDT_DATA               1093
#define IDC_EDT_TEAMHEAD                1093
#define IDC_EDIT_NAMEDATA               1093
#define IDC_EDIT_KILLNAME               1093
#define IDC_EDIT_ITEMAMOUNT             1093
#define IDC_EDIT_MONSTERLEV             1093
#define IDC_GROUP_BTN_5                 1093
#define IDC_EDIT_INFO                   1093
#define IDC_EDIT_BIDVALUE               1093
#define IDC_EDIT_AUCMONEY               1093
#define IDC_EDIT_PAGEAMOUNT             1093
#define IDC_EDIT_OLDNAME                1093
#define IDC_EDIT_BLACKNAME              1093
#define IDC_EDIT_NAME1                  1093
#define IDC_EDIT2                       1094
#define IDC_GROUP_CHK_STOP              1094
#define IDC_TRADE_EDT_MPCMONEY          1094
#define IDC_MPCGOODS_EDT_MONEY          1094
#define IDC_TALK_IMG_MODE               1094
#define IDC_EDT_SECOND                  1094
#define IDC_EDIT_MONEY                  1094
#define IDC_EDIT_MONSTERGROW            1094
#define IDC_EDIT_ITEMNAME               1094
#define IDC_EDIT_TITLE                  1094
#define IDC_EDIT_NOWNAME                1094
#define IDC_EDIT_NAME2                  1094
#define IDC_EDIT3                       1095
#define IDC_TALK_BTN_LOG                1095
#define IDC_GROUP_CHK_MONEY             1095
#define IDC_TALK_BTN_SEND3              1095
#define IDC_TALK_CHK_RUN                1095
#define IDC_EDIT_TASKINFO               1095
#define IDC_EDIT_ITEMMARK               1095
#define IDC_EDIT_MONSTERTYPE            1095
#define IDC_EDIT_NAME3                  1095
#define IDC_EDIT4                       1096
#define IDC_GROUP_CHK_ITEM              1096
#define IDC_TALK_BTN_ACTION             1096
#define IDC_TALK_BTN_SEND4              1096
#define IDC_TALK_CHK_LOOK               1096
#define IDC_TALK_CLEARBTN               1096
#define IDC_EDIT_ITEMSOUL               1096
#define IDC_EDIT_NAME4                  1096
#define IDC_TALK_BTN_SEND5              1097
#define IDC_TALK_BTN_MIPMAP             1097
#define IDC_GROUP_CHK_JION              1097
#define IDC_TALK_BTN_SEND6              1098
#define IDC_TALK_BTN_HELP               1098
#define IDC_COMBO1                      1099
#define IDC_LOG_FILE                    1099
#define IDC_TALK_MYCHAT                 1099
#define IDC_LISTBOX                     1100
#define IDC_SERVER_BTN_OK               1101
#define IDC_TALK_BTN_VIEWEQUIP          1101
#define IDC_SERVER_BTN_EXIT             1102
#define IDC_CONFIRM_BTN_CANCEL          1102
#define IDC_TALK_BTN_TARGETLIST         1102
#define IDC_LOGIN_BTN_OK                1103
#define IDC_TALK_BTN_EMOTIONLIST        1103
#define IDC_LOGIN_BTN_EXIT              1104
#define IDC_NPCBUY_BTN_CLOSE            1104
#define IDC_FRIEND_BTN_DEL              1104
#define IDC_NPCBUY_BTN_FIX              1105
#define IDC_LOGIN_BTN_CANCEL            1105
#define IDC_ROLECHOOSE_IMG1             1106
#define IDC_ROLECHOOSE_MIMG1            1106
#define IDC_NPCBUY_BTN_TALK             1106
#define IDC_ROLECHOOSE_IMG2             1107
#define IDC_ROLECHOOSE_MIMG2            1107
#define IDC_NPCBUY_BTN_ASK              1107
#define IDC_ROLECHOOSE_IMG3             1108
#define IDC_ROLECHOOSE_MIMG3            1108
#define IDC_NPCBUY_BTN_FIX2             1108
#define IDC_ROLECHOOSE_IMG4             1109
#define IDC_ROLECHOOSE_MIMG4            1109
#define IDC_ROLECHOOSE_STA_DATA         1110
#define IDC_ROLECHOOSE_BTN_RETURN       1111
#define IDC_ROLECHOOSE_BTN_OK           1112
#define IDC_ROLECREATE_BTN_OK           1113
#define IDC_BTN_HELP                    1113
#define IDC_ROLECREATE_BTN_RETURN       1114
#define IDC_MPCGOODS_BTN_MONEY          1114
#define IDC_ROLE_BTN9                   1114
#define IDC_BTN_RECORD                  1114
#define IDC_LOGIN_BTN_RECORD            1114
#define IDC_TASK_BTN_ANSWER             1114
#define IDC_NPCBUY_BTN_UP               1114
#define IDC_ROLECHOOSE_WIMG1            1114
#define IDC_MPCBOOTH_BTN_CHANGE1        1114
#define IDC_NPCBOOTH_BTN_BUY1           1114
#define IDC_BTN_OK                      1114
#define IDC_BTN_SORT                    1114
#define IDC_ROLECREATE_BTN_RESET        1114
#define IDC_ROLECREATE_EDT_NAME         1115
#define IDC_ROLE_BTN10                  1115
#define IDC_NPCBUY_BTN_DOWN             1115
#define IDC_ROLECHOOSE_WIMG2            1115
#define IDC_MSGSEND_ALLMSG              1115
#define IDC_MPCBOOTH_BTN_GETBACK1       1115
#define IDC_NPCBOOTH_BTN_BUY2           1115
#define IDC_BTN_DEL                     1115
#define IDC_BTN_RIGHT                   1115
#define IDC_BTN_UP1                     1115
#define IDC_BTN_APPSUB                  1115
#define IDC_CHK_PAGE1                   1115
#define IDC_ROLECREATE_STA_DATA         1116
#define IDC_ROLE_BTN11                  1116
#define IDC_ROLECHOOSE_WIMG3            1116
#define IDC_MSGSEND_SEND                1116
#define IDC_MPCBOOTH_BTN_CHANGE2        1116
#define IDC_NPCBOOTH_BTN_BUY3           1116
#define IDC_BTN_DOWN1                   1116
#define IDC_BTN_MSG1                    1116
#define IDC_BTN_APPNEAR                 1116
#define IDC_CHK_PAGE2                   1116
#define IDC_ROLECREATE_IMG_ROLE         1117
#define IDC_ROLECHOOSE_WIMG4            1117
#define IDC_MPCBOOTH_BTN_GETBACK2       1117
#define IDC_NPCBOOTH_BTN_BUY4           1117
#define IDC_MSGRECEIVE_NEXT             1117
#define IDC_BTN_UP2                     1117
#define IDC_BTN_DEL1                    1117
#define IDC_BTN_REMOVEFUN               1117
#define IDC_CHK_PAGE3                   1117
#define IDC_BTN_HELP1                   1118
#define IDC_MPCBOOTH_BTN_CHANGE3        1118
#define IDC_NPCBOOTH_BTN_BUY5           1118
#define IDC_MSGRECEIVE_PRE              1118
#define IDC_BTN_DOWN2                   1118
#define IDC_BTN_MSG2                    1118
#define IDC_BTN_FUNMOVE                 1118
#define IDC_ROLECREATE_CHK_HUNT         1119
#define IDC_MPCBOOTH_BTN_GETBACK3       1119
#define IDC_NPCBOOTH_BTN_BUY6           1119
#define IDC_MSGRECEIVE_DELALL           1119
#define IDC_BTN_UP3                     1119
#define IDC_BTN_DOWN5                   1119
#define IDC_BTN_DEL2                    1119
#define IDC_ROLECREATE_CHK_FIGHT        1120
#define IDC_MPCBOOTH_BTN_CHANGE4        1120
#define IDC_BTN_DOWN3                   1120
#define IDC_BTN_UP5                     1120
#define IDC_BTN_MSG3                    1120
#define IDC_ROLECREATE_CHK_BRAVE        1121
#define IDC_MPCBOOTH_BTN_GETBACK4       1121
#define IDC_NPCBOOTH_BTN_UP             1121
#define IDC_BTN_UP4                     1121
#define IDC_BTN_DOWN6                   1121
#define IDC_BTN_DEL3                    1121
#define IDC_ROLECREATE_CHK_TAOIST       1122
#define IDC_MPCBOOTH_BTN_CHANGE5        1122
#define IDC_NPCBOOTH_BTN_DOWN           1122
#define IDC_BTN_DOWN4                   1122
#define IDC_BTN_UP6                     1122
#define IDC_ROLECREATE_CHK_KNIGHT       1123
#define IDC_MPCBOOTH_BTN_GETBACK5       1123
#define IDC_NPCBOOTH_BTN_CLOSE          1123
#define IDC_BTN_DOWN7                   1123
#define IDC_MPCBOOTH_BTN_CHANGE6        1124
#define IDC_NPCBOOTH_BTN_CLOSEB         1124
#define IDC_BTN_UP7                     1124
#define IDC_NPCBUY_GRI_SALE             1125
#define IDC_MPCBOOTH_BTN_GETBACK6       1125
#define IDC_BTN_DOWN8                   1125
#define IDC_NPCBUY_STA_PRICE            1126
#define IDC_NPCBUY_GRI_OWNER            1127
#define IDC_BTN_RIGHT2                  1127
#define IDC_NPCBUY_STA_MONEY            1128
#define IDC_BTN_RIGHT1                  1128
#define IDC_NPCBUY_BTN_OK               1129
#define IDC_BTN_RIGHT3                  1129
#define IDC_ROLE_STA_1                  1130
#define IDC_ROLE_STA_2                  1131
#define IDC_MPCGOODS_GOODBOX            1131
#define IDC_MPCGOODS_STONEBOX           1132
#define IDC_ROLE_STA_3                  1133
#define IDC_ROLE_STA_4                  1134
#define IDC_SETUP_BTN_DELETE            1134
#define IDC_ROLE_STA_5                  1135
#define IDC_MPCGOODS_STA_MONEY          1135
#define IDC_MPCGOODS_STA_HEAVY          1136
#define IDC_MPCGOODS_BTN_CLOSE          1137
#define IDC_TRADE_BTN_CLOSE             1138
#define IDC_ROLE_STA_6                  1139
#define IDC_TRADE_BTN_MPCAGREE          1139
#define IDC_TRADE_GRI_NPC               1140
#define IDC_TRADE_GRI_MPC               1141
#define IDC_TRADE_STA_NPCMONEY          1142
#define IDC_ROLE_STA_7                  1143
#define IDC_CONFIRM_BTN_OK              1143
#define IDC_TRADE_STA_NPCPAGE           1143
#define IDC_ROLE_STA_8                  1144
#define IDC_TRADE_STA_MPCPAGE           1144
#define IDC_ROLE_STA_9                  1145
#define IDC_TRADE_BTN_CLEAR             1145
#define IDC_SETUP_PIC1                  1145
#define IDC_TRADE_BTN_MONEYMPCOK        1145
#define IDC_ROLE_STA_10                 1146
#define IDC_SETUP_PIC2                  1146
#define IDC_TRADE_STA_NPCNAME           1146
#define IDC_ROLE_STA_11                 1147
#define IDC_TRADE_STA_NPCALLPAGE        1147
#define IDC_ROLE_STA_12                 1148
#define IDC_TRADE_STA_MPCALLPAGE        1148
#define IDC_TRADE_STA_MPCNAME           1148
#define IDC_ROLE_STA_13                 1149
#define IDC_ROLE_BTN8                   1149
#define IDC_TRADE_BTN_CLEAR1            1149
#define IDC_TRADE_BTN_MONEYNPCOK        1149
#define IDC_ROLE_BTN_BASE               1150
#define IDC_TRADE_BTN_NPCOK             1150
#define IDC_MISSION_IMA_HEAD            1151
#define IDC_ROLE_BTN_MORE               1151
#define IDC_FRIEND_BTN_ADD              1152
#define IDC_ROLE_STA_14                 1152
#define IDC_MISSION_IMA_GEAR            1153
#define IDC_FRIEND_LST_DATA             1153
#define IDC_ROLE_STA_15                 1153
#define IDC_HOTKEY_BTN_SAVE             1153
#define IDC_MISSION_IMA_NECK            1154
#define IDC_FRIEND_BTN_CLOSE            1154
#define IDC_DEPOT_BTN_ADD               1154
#define IDC_ROLE_STA_16                 1154
#define IDC_HOTKEY_BTN_REVERT           1154
#define IDC_MISSION_IMA_LHAND           1155
#define IDC_DEPOT_CLOSE                 1155
#define IDC_ROLE_STA_17                 1155
#define IDC_HOTKEY_LST_PARENT           1155
#define IDC_FRIEND_BTN_RESUME           1155
#define IDC_MISSION_IMA_FOOT            1156
#define IDC_DEPOT_STA_LAY               1156
#define IDC_ROLE_STA_18                 1156
#define IDC_HOTKEY_LST_CHILD            1156
#define IDC_BTN_SORTONLINE              1156
#define IDC_DEPOT_CLOSEB                1157
#define IDC_ROLE_STA_19                 1157
#define IDC_HOTKEY_BTN_DEL              1157
#define IDC_BTN_SORTNAME                1157
#define IDC_MISSION_IMA_RHAND           1158
#define IDC_DEPOT_GRI_LAY               1158
#define IDC_MISSION_IMA_BODY            1159
#define IDC_SKILL_IMA1                  1160
#define IDC_SKILL_IMA2                  1161
#define IDC_SKILL_IMA3                  1162
#define IDC_SKILL_IMA4                  1163
#define IDC_SKILL_IMA5                  1164
#define IDC_SKILL_IMA6                  1165
#define IDC_SKILL_IMA7                  1166
#define IDC_SKILL_IMA8                  1167
#define IDC_SKILL_IMA11                 1168
#define IDC_SKILL_IMA22                 1169
#define IDC_SKILL_IMA33                 1170
#define IDC_SKILL_IMA44                 1171
#define IDC_SKILL_IMA55                 1172
#define IDC_SKILL_IMA66                 1173
#define IDC_SKILL_IMA77                 1174
#define IDC_SKILL_IMA88                 1175
#define IDC_SKILL_BTN_Z                 1176
#define IDC_SKILL_BTN_M                 1177
#define IDC_SKILL_BTN_J                 1178
#define IDC_BTN_CLOSE                   1180
#define IDC_TRADE_STA_NPCAGREE          1181
#define IDC_BTN_UPALL                   1181
#define IDC_BTN_ZOOMIN                  1181
#define IDC_TALK_BTN_G                  1182
#define IDC_BTN_UPCUR                   1182
#define IDC_BTN_ZOOMOUT                 1182
#define IDC_BTN_BIGOUT                  1182
#define IDC_TALK_BTN_S                  1183
#define IDC_TALK_BTN_TALK               1183
#define IDC_BTN_UPFRIEND                1183
#define IDC_TALK_BTN_D                  1184
#define IDC_MAGIC_IMG1                  1184
#define IDC_TALK_BTN_ADD                1184
#define IDC_BTN_UPTEAM                  1184
#define IDC_TALK_BTN_B                  1185
#define IDC_TALK_BTN_LIST               1185
#define IDC_MAGIC_IMG6                  1185
#define IDC_BTN_UPPRIVATE               1185
#define IDC_TALK_BTN_H                  1186
#define IDC_XP_IMG1                     1186
#define IDC_BTN_UPKNIGHT                1186
#define IDC_XP_IMG2                     1187
#define IDC_BTN_ALL                     1187
#define IDC_TALK_BTN_GM                 1187
#define IDC_XP_IMG3                     1188
#define IDC_BTN_CUR                     1188
#define IDC_TALK_BTN_W                  1188
#define IDC_XP_IMG4                     1189
#define IDC_BTN_FRIEND                  1189
#define IDC_XP_IMG5                     1190
#define IDC_BTN_TEAM                    1190
#define IDC_PK_FREE                     1191
#define IDC_XP_IMG6                     1191
#define IDC_BTN_PRIVATE                 1191
#define IDC_CHK_TEAM                    1191
#define IDC_XP_IMG7                     1192
#define IDC_BTN_KNIGHT                  1192
#define IDC_XP_IMG8                     1193
#define IDC_BTN_CLEAR                   1193
#define IDC_XP_IMG9                     1194
#define IDC_BTN_RESUME                  1194
#define IDC_XP_IMG10                    1195
#define IDC_BTN_MIN                     1196
#define IDC_SLI_LINE                    1198
#define IDC_BTN_MSGHIDE                 1198
#define IDC_CONFIRM_EDT_DATA            1199
#define IDC_BTN_SYSHIDE                 1199
#define IDC_FRDSTATE_BTN_CLOSE          1200
#define IDC_CONFIRM_EDT_NAME            1200
#define IDC_STA1                        1201
#define IDC_STA2                        1202
#define IDC_STA3                        1203
#define IDC_STA4                        1204
#define IDC_FRDSTATE_BTN_DEL            1205
#define IDC_STA_NOBILITY                1205
#define IDC_STA5                        1206
#define IDC_IMPROVE_IMA_GOOD            1206
#define IDC_STA6                        1207
#define IDC_IMPROVE_IMA_GEM             1207
#define IDC_NPCFACE_IMA2                1207
#define IDC_STA7                        1208
#define IDC_IMPROVE_BTN_IMP             1208
#define IDC_NPCFACE_IMA3                1208
#define IDC_EMBED_IMA_GEM2              1208
#define IDC_EMBED_IMA_MONSTER           1208
#define IDC_IMPROVE_BTN_CLOSE           1209
#define IDC_NPCFACE_IMA4                1209
#define IDC_EMBED_BTN_EMBED             1209
#define IDC_NPCFACE_BTN_CLOSE           1210
#define IDC_EMBED_BTN_TACKOFF           1210
#define IDC_EMBED_BTN_CANCEL            1210
#define IDC_NPCFACE_IMA5                1211
#define IDC_NPCFACE_IMA6                1212
#define IDC_NPCFACE_IMA1                1213
#define IDC_NPCFACE_BTN_AGREE           1214
#define IDC_FRDSTATE_IMAFACE            1214
#define IDC_NPCFACE_BTN_UP              1215
#define IDC_FACTION_CLOSE               1215
#define IDC_NPCFACE_BTN_DOWN            1216
#define IDC_KONGFU_IMG1                 1216
#define IDC_KONGFU_IMG2                 1217
#define IDC_KONGFU_IMG3                 1218
#define IDC_KONGFU_IMG4                 1219
#define IDC_KONGFU_IMG5                 1220
#define IDC_KONGFU_IMG6                 1221
#define IDC_BUTTON_CLOSE                1221
#define IDC_KONGFU_IMG7                 1222
#define IDC_ROLECREATE_BTN_EXIT         1222
#define IDC_KONGFU_IMG8                 1223
#define IDC_KONGFU_IMG9                 1224
#define IDC_LOGIN_GROUP1                1224
#define IDC_BTN_CANCELALLOT             1224
#define IDC_KONGFU_IMG10                1225
#define IDC_LOGIN_SERVER1               1225
#define IDC_LOGIN_SERVER2               1226
#define IDC_LOGIN_SERVER3               1227
#define IDC_LOGIN_EDTIMG                1228
#define IDC_LOGIN_ROLEIMG               1229
#define IDC_LOGIN_SERVER4               1230
#define IDC_LOGIN_SERVER5               1231
#define IDC_LOGIN_SERVER6               1232
#define IDC_LOGIN_SERVER7               1233
#define IDC_LOGIN_SERVER8               1234
#define IDC_LOGIN_GROUP5                1234
#define IDC_LOGIN_SERVER9               1235
#define IDC_LOGIN_SERVER10              1236
#define IDC_LOGIN_SERVER11              1237
#define IDC_LOGIN_SERVER12              1238
#define IDC_LOGIN_SERVER13              1239
#define IDC_LOGIN_GROUPIMG              1239
#define IDC_LOGIN_SERVER14              1240
#define IDC_LOGIN_SERVER15              1241
#define IDC_LOGIN_SERVER16              1242
#define IDC_LOGIN_SERVER17              1243
#define IDC_LOGIN_SERVER18              1244
#define IDC_LOGIN_SERVER19              1245
#define IDC_LOGIN_SERVER20              1246
#define IDC_STCSVR1                     1247
#define IDC_LOGIN_GROUP2                1248
#define IDC_LOGIN_GROUP3                1249
#define IDC_LOG_RECORD                  1249
#define IDC_LOGIN_GROUP4                1250
#define IDC_LOG_DEL                     1250
#define IDC_LOG_DELALL                  1251
#define IDC_STCSVR2                     1252
#define IDC_LOG_CLOSE                   1252
#define IDC_STCSVR3                     1253
#define IDC_EMBED_IMA_GOOD              1253
#define IDC_LOG_LOGALL                  1253
#define IDC_STCSVR4                     1254
#define IDC_EMBED_IMA_GEM1              1254
#define IDC_LOG_LOGG                    1254
#define IDC_STCSVR5                     1255
#define IDC_EMBED_CLOSE                 1255
#define IDC_LOG_LOGS                    1255
#define IDC_STCSVR6                     1256
#define IDC_EMBED_CLOSES                1256
#define IDC_LOG_LOGFAC                  1256
#define IDC_STCSVR7                     1257
#define IDC_FACTION_CLOSEB              1257
#define IDC_LOG_LOGFRD                  1257
#define IDC_STCSVR8                     1258
#define IDC_TRADE_CLOSEB                1258
#define IDC_BTN_CANCEL                  1258
#define IDC_LOG_LOGTEAM                 1258
#define IDC_STCSVR9                     1259
#define IDC_SKILL_CLOSEB                1259
#define IDC_LOG_LOGSYS                  1259
#define IDC_STCSVR10                    1260
#define IDC_HELP_MORE                   1260
#define IDC_LOG_LOGMY                   1260
#define IDC_STCSVR11                    1261
#define IDC_SETUP_BTN_CLOSES            1261
#define IDC_STCSVR12                    1262
#define IDC_HOTKEY_BTN_CHANGE           1262
#define IDC_STCSVR13                    1263
#define IDC_HOTKEY_CLOSEB               1263
#define IDC_STCSVR14                    1264
#define IDC_HOTKEY_CLOSE                1264
#define IDC_STCSVR15                    1265
#define IDC_HOTKEY_STA_OLD              1265
#define IDC_STCSVR16                    1266
#define IDC_HOTKEY_BTN_SET              1266
#define IDC_STCSVR17                    1267
#define IDC_STCSVR18                    1268
#define IDC_STCSVR19                    1269
#define IDC_STCSVR20                    1270
#define IDC_HOTKEY                      1274
#define IDC_MAGIC_BTN_UP                1275
#define IDC_MAGIC_BTN_DOWN              1276
#define IDC_XP_BTN_UP                   1277
#define IDC_XP_BTN_DOWN                 1278
#define IDC_KONGFU_BTN_UP               1279
#define IDC_KONGFU_BTN_DOWN             1280
#define IDC_MSGSEND_BTN_CLOSES          1281
#define IDC_MSGSEND_CLOSEB              1283
#define IDC_MSGSEND_NAME                1284
#define IDC_MPCBOOTH_BTN_CLOSES         1286
#define IDC_MPCBOOTH_CLOSEB             1287
#define IDC_MPCBOOTH_BTN_UP             1288
#define IDC_MPCBOOTH_BTN_DOWN           1289
#define IDC_MPCBOOTH_BTN_RECALL         1290
#define IDC_MPCBOOTH_BTN_HAWK           1291
#define IDC_MPCBOOTH_IMA_GOOD1          1304
#define IDC_MPCBOOTH_IMA_GOOD2          1305
#define IDC_MPCBOOTH_IMA_GOOD3          1306
#define IDC_MPCBOOTH_IMA_GOOD4          1307
#define IDC_MPCBOOTH_IMA_GOOD5          1308
#define IDC_MPCBOOTH_IMA_GOOD6          1309
#define IDC_STA_PRICE1                  1310
#define IDC_STA_PRICE2                  1311
#define IDC_NPCBOOTH_IMA_GOOD1          1311
#define IDC_STA_PRICE3                  1312
#define IDC_NPCBOOTH_IMA_GOOD2          1312
#define IDC_STA_PRICE4                  1313
#define IDC_NPCBOOTH_IMA_GOOD3          1313
#define IDC_STA_PRICE5                  1314
#define IDC_NPCBOOTH_IMA_GOOD4          1314
#define IDC_STA_PRICE6                  1315
#define IDC_NPCBOOTH_IMA_GOOD5          1315
#define IDC_NPCBOOTH_IMA_GOOD6          1316
#define IDC_STA_PRICE22                 1317
#define IDC_STA_PRICE33                 1318
#define IDC_STA_PRICE44                 1319
#define IDC_STA_PRICE55                 1320
#define IDC_STA_PRICE66                 1321
#define IDC_STA_PRICE11                 1322
#define IDC_HAWK_BTN_CLOSES             1323
#define IDC_HAWK_BTN_AGREE              1324
#define IDC_MSGRECEIVE_BTN_CLOSES       1328
#define IDC_MSGRECEIVE_CLOSEB           1329
#define IDC_MSGRECEIVE_NAME             1331
#define IDC_MSGRECEIVE_DATA             1332
#define IDC_MSGRECEIVE_REVERT           1333
#define IDC_CHAT_CLOSEB                 1334
#define IDC_MSGRECEIVE_TIME             1334
#define IDC_CHAT_BTN_CLOSES             1335
#define IDC_CHAT_BTN_RECORD             1336
#define IDC_CHAT_BTN_SIFT               1337
#define IDC_FACTION_EDT_DATA            1337
#define IDC_OTHER_BTN_DEL               1337
#define IDC_CHAT_CHK_G                  1338
#define IDC_BLACK_LST_DATA              1338
#define IDC_BLACK_BTN_CLOSES            1339
#define IDC_CHAT_BTN_LEVWORD            1339
#define IDC_CHAT_IMG_GC                 1339
#define IDC_CHAT_CHK_B                  1340
#define IDC_BLACK_BTN_DEL               1340
#define IDC_CHAT_CHK_D                  1341
#define IDC_BLACK_BTN_ADD               1341
#define IDC_CHAT_CHK_H                  1342
#define IDC_BLACK_CLOSEB                1342
#define IDC_BLACK_EDT_NAME              1343
#define IDC_CHAT_CHK_S                  1343
#define IDC_LEVWORD_BTN_CLOSES          1344
#define IDC_CHAT_CHK_SF                 1344
#define IDC_LEVWORD_CLOSEB              1345
#define IDC_CHAT_IMG_DC                 1345
#define IDC_LEVWORD_BTN_SEND            1346
#define IDC_CHAT_IMG_SC                 1346
#define IDC_LEVWORD_BTN_WATCH           1347
#define IDC_CHAT_IMG_BC                 1347
#define IDC_LEVWORD_BTN_UP              1348
#define IDC_CHAT_IMG_HC                 1348
#define IDC_LEVWORD_BTN_DOWN            1349
#define IDC_CHAT_IMG_CC1                1349
#define IDC_CHAT_IMG_CC2                1350
#define IDC_LEVWORD_BTN_DEL             1351
#define IDC_CHAT_IMG_CC3                1351
#define IDC_LEVWORD_BTN_FLASH           1352
#define IDC_CHAT_IMG_CC4                1352
#define IDC_LEVWORD_BTN_TRADE           1353
#define IDC_CHAT_IMG_CC5                1353
#define IDC_LEVWORD_BTN_FRIEND          1354
#define IDC_CHAT_IMG_CC6                1354
#define IDC_LEVWORD_BTN_GROUP           1355
#define IDC_CHAT_IMG_CC7                1355
#define IDC_LEVWORD_BTN_FACTION         1356
#define IDC_CHAT_IMG_CC8                1356
#define IDC_LEVWORD_BTN_OTHER           1357
#define IDC_CHAT_CHK_Z                  1357
#define IDC_LEVWORD_LST_LIST            1358
#define IDC_CHAT_IMG_ZC                 1358
#define IDC_LEVWORD_EDT_DATA            1360
#define IDC_EFFIGY_CLOSES               1361
#define IDC_EFFIGY_CLOSE                1362
#define IDC_EFFIGY_OK                   1363
#define IDC_LAY_BTN_CLOSES              1363
#define IDC_EFFIGY_PANDP                1364
#define IDC_LAY_CLOSEB                  1364
#define IDC_EFFIGY_LEFT                 1365
#define IDC_EFFIGY_RIGHT                1366
#define IDC_LAY_LEFT                    1367
#define IDC_LAY_RIGHT                   1368
#define IDC_FACTION_LST_LIST            1370
#define IDC_FACTION_LEFT                1371
#define IDC_FACTION_RIGHT               1372
#define IDC_OTHER_BTN_LAY               1373
#define IDC_BTN_CLOSEB                  1374
#define IDC_FACSTATE_BTN_CLOSE          1375
#define IDC_NPCEQUIP_IMA_HEAD           1376
#define IDC_NPCEQUIP_IMA_GEAR           1377
#define IDC_NPCEQUIP_IMA_NECK           1378
#define IDC_NPCEQUIP_IMA_LHAND          1379
#define IDC_NPCEQUIP_IMA_FOOT           1380
#define IDC_NPCEQUIP_IMA_RHAND          1381
#define IDC_NPCEQUIP_IMA_BODY           1382
#define IDC_NPCEQUIP_CLOSEB             1383
#define IDC_NPCEQUIP_CLOSE              1384
#define IDC_TRADE_BTN_NPCU              1385
#define IDC_TRADE_BTN_NPCD              1386
#define IDC_TRADE_BTN_MPCU              1387
#define IDC_DEPOT_BTN_U                 1387
#define IDC_TRADE_BTN_MPCD              1388
#define IDC_DEPOT_BTN_D                 1388
#define IDC_STA_NAME                    1389
#define IDC_STA_MATE                    1390
#define IDC_DEPOT_STA_PAGE              1390
#define IDC_STA_2                       1390
#define IDC_STA_LEV                     1390
#define IDC_STA_RES                     1390
#define IDC_STA_POSX                    1390
#define IDC_DEPOT_STA_ALLPAGE           1391
#define IDC_STA_3                       1391
#define IDC_STA_STIRPS                  1391
#define IDC_STA_CEL                     1391
#define IDC_STA_POSY                    1391
#define IDC_IMPROVE_BTN_CLOSEB          1392
#define IDC_STA_ENE                     1392
#define IDC_STA_NAME4                   1392
#define IDC_DICE_IMA_ALL1               1393
#define IDC_STA_MAIN                    1393
#define IDC_STA_NAME5                   1393
#define IDC_DICE_IMA_ALL2               1394
#define IDC_STA_WORK                    1394
#define IDC_STA_MAGATK                  1394
#define IDC_STA_NAME6                   1394
#define IDC_DICE_IMA_ALL3               1395
#define IDC_STA_FERE                    1395
#define IDC_STA_ATK                     1395
#define IDC_STA_NAME7                   1395
#define IDC_DICE_IMA_ALL4               1396
#define IDC_STA_DUKE                    1396
#define IDC_STA_BURDEN                  1396
#define IDC_DICE_IMA_ALL5               1397
#define IDC_STA_MVALUE                  1397
#define IDC_STA_MAGDEF                  1397
#define IDC_DICE_IMA_ALL6               1398
#define IDC_STA_KNIGHT                  1398
#define IDC_STA_DEF                     1398
#define IDC_DICE_IMA_4                  1399
#define IDC_STA_MERLEV                  1399
#define IDC_DICE_IMA_5                  1400
#define IDC_STA_MEREXP                  1400
#define IDC_DICE_IMA_6                  1401
#define IDC_DICE_IMA_7                  1402
#define IDC_DICE_IMA_8                  1403
#define IDC_DICE_IMA_9                  1404
#define IDC_DICE_IMA_10                 1405
#define IDC_DICE_IMA_11                 1406
#define IDC_DICE_IMA_12                 1407
#define IDC_DICE_IMA_13                 1408
#define IDC_DICE_IMA_14                 1409
#define IDC_DICE_IMA_15                 1410
#define IDC_DICE_IMA_16                 1411
#define IDC_DICE_IMA_17                 1412
#define IDC_DICE_IMA_SMALL              1413
#define IDC_DICE_IMA_BIG                1414
#define IDC_DICE_BTN_CHIPIN             1415
#define IDC_DICE_BTN_HIDE               1416
#define IDC_DICE_BTN_CHIP100            1417
#define IDC_DICE_BTN_CHIP1000           1418
#define IDC_DICE_BTN_CHIP10000          1419
#define IDC_DICE_STA_MPC                1420
#define IDC_DICE_STA_ALL                1421
#define IDC_DICE_BTN_DICELIST           1422
#define IDC_DICELIST_LIST               1423
#define IDC_DICE_STA_CHIP               1423
#define IDC_ENEMY_BTN_CLOSE             1424
#define IDC_DICE_BTN_RESUME             1424
#define IDC_ENEMY_LST_DATA              1425
#define IDC_ENMSTATE_BTN_CLOSE          1426
#define IDC_ENMSTATE_IMAFACE            1427
#define IDC_ENMSTATE_BTN_DEL            1428
#define IDC_STA_1                       1429
#define IDC_INSHELP_BTN_CLOSES          1430
#define IDC_INSHELP_BTN_MORE            1431
#define IDC_INSHELP_BTN_HELP            1432
#define IDC_ENEMY_BTN_RESUME            1432
#define IDC_ENEMY_BTN_ADD               1432
#define IDC_INSHELP_BTN_CLOSEB          1433
#define IDC_ENEMY_BTN_FRIEND            1433
#define IDC_INSHELP_BTN_TIP             1434
#define IDC_TALKACT_BTN_HELP            1434
#define IDC_ENEMY_BTN_ENEMY             1434
#define IDC_INSHELP_BTN_PAGEUP          1435
#define IDC_TALKACT_BTN_CLOSEB          1435
#define IDC_ENEMY_BTN_TEACHER           1435
#define IDC_INSHELP_BTN_PAGEDOWN        1436
#define IDC_TALKACT_BTN_PAGEUP          1436
#define IDC_EXP_LEV                     1436
#define IDC_TALKACT_BTN_PAGEDOWN        1437
#define IDC_EXP_EXP                     1437
#define IDC_IMG_HEAD                    1438
#define IDC_STA_POWER                   1439
#define IDC_IMG_HONOR1                  1439
#define IDC_STA_LEFTPNT                 1440
#define IDC_IMG_HONORB                  1440
#define IDC_STA_LEV1                    1440
#define IDC_STA_HP                      1441
#define IDC_IMG_HONOR2                  1441
#define IDC_STA_SEX1                    1441
#define IDC_STA_MAGIC                   1442
#define IDC_IMG_HONOR3                  1442
#define IDC_STA_PRO1                    1442
#define IDC_IMG_HONOR4                  1443
#define IDC_STA_STIRPS1                 1443
#define IDC_IMG_HONOR5                  1444
#define IDC_STA_LEV2                    1444
#define IDC_IMG_HONOR6                  1445
#define IDC_STA_SEX2                    1445
#define IDC_IMG_HONOR7                  1446
#define IDC_STA_PRO2                    1446
#define IDC_IMG_HONOR8                  1447
#define IDC_STA_STIRPS2                 1447
#define IDC_IMG_HEAD1                   1448
#define IDC_IMG_PET                     1448
#define IDC_IMG_HEAD2                   1449
#define IDC_IMG_SHOE                    1449
#define IDC_IMG_HEAD3                   1450
#define IDC_IMG_MOUNT                   1450
#define IDC_IMG_HEAD4                   1451
#define IDC_STA_LEV3                    1451
#define IDC_IMG_HEAD5                   1452
#define IDC_STA_SEX3                    1452
#define IDC_IMG_HEAD6                   1453
#define IDC_STA_PRO3                    1453
#define IDC_IMG_HEAD7                   1454
#define IDC_STA_STIRPS3                 1454
#define IDC_IMG_HEAD8                   1455
#define IDC_IMG_HEADB                   1456
#define IDC_STA_TITLE                   1457
#define IDC_IMG_HEADS                   1458
#define IDC_BTN_RANDOM                  1459
#define IDC_BTN_CHOOSE                  1460
#define IDC_BTN_SHOW                    1462
#define IDC_BTN_LEFT                    1463
#define IDC_BTN_MALE                    1464
#define IDC_BTN_FEMALE                  1465
#define IDC_IMG_BK                      1466
#define IDC_BTN_LEFT2                   1466
#define IDC_IMG_OTHER                   1467
#define IDC_IMG_PRO                     1467
#define IDC_BTN_LEFT3                   1467
#define IDC_IMG_NUMEN                   1468
#define IDC_IMG_LWEAPON                 1469
#define IDC_IMG_STIRPS                  1469
#define IDC_IMG_NECK                    1470
#define IDC_IMG_GEAR                    1471
#define IDC_IMG_BODY                    1472
#define IDC_IMG_RWEAPON                 1473
#define IDC_STA_MONEY                   1474
#define IDC_STA_HEAVY                   1475
#define IDC_STA_NAME1                   1476
#define IDC_STA_NAME2                   1477
#define IDC_BTN_UP                      1477
#define IDC_STA_NAME3                   1478
#define IDC_BTN_DOWN                    1478
#define IDC_STA_FORCE                   1479
#define IDC_STA_DESC1                   1479
#define IDC_STA_NAME8                   1479
#define IDC_IMG_GOOD                    1480
#define IDC_STA_NAME9                   1480
#define IDC_STA_DESCM2                  1480
#define IDC_PRG_HERO_HP                 1481
#define IDC_STA_DESC2                   1481
#define IDC_STA_NAME10                  1481
#define IDC_STA_DESCM3                  1481
#define IDC_STA_ENERGY                  1482
#define IDC_PRG_EXP                     1482
#define IDC_STA_DESC3                   1482
#define IDC_STA_NAME11                  1482
#define IDC_STA_EXP1                    1483
#define IDC_STA_NAME12                  1483
#define IDC_STA_EXP2                    1484
#define IDC_CHK_KNIGHTAGE               1484
#define IDC_STA_NAME13                  1484
#define IDC_STA_EXP3                    1485
#define IDC_CHK_TEACHER                 1485
#define IDC_BTN_BASIC                   1485
#define IDC_STA_NAME14                  1485
#define IDC_PRG_HERO_MP                 1486
#define IDC_STA_EXP4                    1486
#define IDC_CHK_FRIEND                  1486
#define IDC_BTN_SUB                     1486
#define IDC_BTN_DELFRD                  1486
#define IDC_STA_NAME15                  1486
#define IDC_PRG_HERO_FORCE              1487
#define IDC_STA_EXP5                    1487
#define IDC_BTN_CONNECT                 1487
#define IDC_BTN_DELENM                  1487
#define IDC_STA_DESCM4                  1487
#define IDC_PRG_HERO_HEAVY              1488
#define IDC_STA_EXP6                    1488
#define IDC_BTN_MEMBER                  1488
#define IDC_BTN_ADDENM                  1488
#define IDC_PRG_HERO_XP                 1488
#define IDC_PRG_PET_HP                  1489
#define IDC_STA_EXP7                    1489
#define IDC_BTN_ARMY                    1489
#define IDC_PRG_HERO_FORCE2             1489
#define IDC_PRG_PET_MP                  1490
#define IDC_STA_DESC4                   1490
#define IDC_PRG_HERO_XP2                1490
#define IDC_PRG_PET_EXP                 1491
#define IDC_STA_DESC5                   1491
#define IDC_STA_DESC6                   1492
#define IDC_STA_DESC7                   1493
#define IDC_STA_COLONEL                 1493
#define IDC_STA_JOB                     1494
#define IDC_STA_SUB                     1494
#define IDC_STA_EXPLOIT                 1495
#define IDC_EDT_MONEY                   1495
#define IDC_BTN_ADDFRD                  1496
#define IDC_STA_KNIGHTAGE               1496
#define IDC_STA_MEMNUM                  1497
#define IDC_BTN_DELMEM                  1497
#define IDC_BTN_MEDAL                   1498
#define IDC_BTN_CHNAGE1                 1499
#define IDC_STA_MEDAL                   1499
#define IDC_BTN_CHANGE2                 1500
#define IDC_BTN_REMOVE                  1501
#define IDC_BTN_BUILD                   1502
#define IDC_BTN_REMOVECON               1503
#define IDC_BTN_TEACHER                 1504
#define IDC_BTN_LEV                     1505
#define IDC_BTN_ONLINE                  1506
#define IDC_BTN_BREAK                   1507
#define IDC_BTN_LEVWORD                 1508
#define IDC_BTN_BLOOD                   1509
#define IDC_LST_ENEMY                   1511
#define IDC_LST_FRIEND                  1512
#define IDC_LST_MEMBER                  1513
#define IDC_EDT_1                       1514
#define IDC_EDT_2                       1515
#define IDC_DEPOT_BTN_UP                1515
#define IDC_DEPOT_BTN_DOWN              1516
#define IDC_IMG_EMBLEM1                 1517
#define IDC_IMG_EMBLEM2                 1518
#define IDC_IMG_EMBLEM3                 1519
#define IDC_IMG_EMBLEM4                 1520
#define IDC_IMG_EMBLEM5                 1521
#define IDC_IMG_EMBLEM6                 1522
#define IDC_PROGRESS1                   1523
#define IDC_SEVER_PRS1                  1523
#define IDC_PROGRESS_HP1                1523
#define IDC_PROGRESS2                   1524
#define IDC_BTN_CALL                    1524
#define IDC_SEVER_PRS2                  1524
#define IDC_PROGRESS_EXP1               1524
#define IDC_PROGRESS3                   1525
#define IDC_BTN_CHANGE                  1525
#define IDC_SEVER_PRS3                  1525
#define IDC_PROGRESS_XP1                1525
#define IDC_BTN_MAGIC                   1525
#define IDC_PROGRESS4                   1526
#define IDC_BTN_DROP                    1526
#define IDC_SEVER_PRS4                  1526
#define IDC_PROGRESS_HP2                1526
#define IDC_SEVER_PRS5                  1527
#define IDC_BTN_RIDEON                  1527
#define IDC_PROGRESS_EXP2               1527
#define IDC_PROGRESS_XP2                1528
#define IDC_BTN_CALLOUT                 1528
#define IDC_IMG_MONSTER                 1529
#define IDC_PROGRESS_HP3                1529
#define IDC_GRI_SKILL                   1530
#define IDC_PROGRESS_EXP3               1530
#define IDC_PROGRESS_XP3                1531
#define IDC_PROGRESS_HP4                1532
#define IDC_GRI_EGGS                    1533
#define IDC_PROGRESS_EXP4               1533
#define IDC_PROGRESS_XP4                1534
#define IDC_STATIC_LEVEL                1536
#define IDC_MONSTER_LEVEL               1536
#define IDC_STATIC_MASTER               1537
#define IDC_MONSTER_MASTER              1537
#define IDC_STATIC_EXP                  1538
#define IDC_MONSTER_EXP                 1538
#define IDC_STATIC_MONSTER3             1539
#define IDC_STATIC_MONSTER1             1540
#define IDC_STATIC_MONSTER2             1541
#define IDC_STATIC_NAME                 1542
#define IDC_MONSTER_NAME                1542
#define IDC_STATIC_HP                   1543
#define IDC_MONSTER_HP                  1543
#define IDC_STATIC_FIGHT                1544
#define IDC_MONSTER_FIGHT               1544
#define IDC_STATIC_MAGIC                1545
#define IDC_MONSTER_MAGIC               1545
#define IDC_STATIC_SMART                1546
#define IDC_MONSTER_SMART               1546
#define IDC_STATIC_FIGHTDEF             1547
#define IDC_MONSTER_FIGHTDEF            1547
#define IDC_STATIC_MAGICDEF             1548
#define IDC_MONSTER_MAGICDEF            1548
#define IDC_ROLE_FACTION                1549
#define IDC_MONSTER_GROW                1549
#define IDC_ROLE_XP                     1550
#define IDC_MONSTER_POTENTIAL           1550
#define IDC_ROLE_MP                     1551
#define IDC_ROLE_AVOID                  1553
#define IDC_ROLE_HP                     1554
#define IDC_ROLE_FIGHT                  1555
#define IDC_ROLE_MAGIC                  1556
#define IDC_ROLE_FIGHTDEF               1557
#define IDC_ROLE_MAGICDEF               1558
#define IDC_ROLE_NAME                   1559
#define IDC_ROLE_LEVEL                  1560
#define IDC_QUERY_BTN_UP                1561
#define IDC_QUERY_BTN_DOWN              1562
#define IDC_QUERY_NAME                  1563
#define IDC_IMG_MANTLE                  1564
#define IDC_IMG_WEAPON                  1565
#define IDC_STA_PK                      1566
#define IDC_STA_FAMOR                   1567
#define IDC_STA_HA                      1569
#define IDC_STA_STRONG                  1570
#define IDC_STA_AMOUNT                  1571
#define IDC_STA_SMART                   1572
#define IDC_STA_POTENTIAL               1573
#define IDC_GRI_STONEQ                  1575
#define IDC_STONE_GRI1                  1577
#define IDC_STONE_GRI2                  1578
#define IDC_CHK_SHADOW                  1578
#define IDC_STONE_GRI3                  1579
#define IDC_CHK_ROLENAME                1579
#define IDC_CHK_SOUND                   1579
#define IDC_STONE_GRI4                  1580
#define IDC_CHK_WEATHER                 1580
#define IDC_CHK_MUSIC                   1580
#define IDC_STONE_GRI5                  1581
#define IDC_STONE_GRI6                  1582
#define IDC_BTN_SOUNDLEFT               1582
#define IDC_STONE_GRI7                  1583
#define IDC_BTN_SOUNDRIGHT              1583
#define IDC_STONE_GRI8                  1584
#define IDC_BTN_MUSICLEFT               1584
#define IDC_STONE_GRI0                  1584
#define IDC_BTN_MUSICRIGHT              1585
#define IDC_STA_SOUND                   1588
#define IDC_STA_MUSIC                   1589
#define IDC_STA_KEY                     1590
#define IDC_BTN_SETKEY                  1591
#define IDC_BTN_RESETKEYS               1592
#define IDC_LIST_HOTKEYM                1593
#define IDC_LIST_HOTKEYN                1594
#define IDC_COLOR_GRI                   1596
#define IDC_BTN_COLOR1                  1596
#define IDC_BTN_PUB                     1597
#define IDC_BTN_SEC                     1598
#define IDC_LIST1                       1598
#define IDC_LIST_LEVWORD                1598
#define IDC_LIST_PLAYERTASK             1598
#define IDC_LIST_REQLEV                 1598
#define IDC_LIST_TBOARD                 1598
#define IDC_LIST_SECSCHOOL              1598
#define IDC_LIST_TXTACTION              1598
#define IDC_LIST_TALKTARGET             1598
#define IDC_MEMBER_LIST                 1598
#define IDC_LIST_ROOMINFO               1598
#define IDC_BTN_COLOR2                  1599
#define IDC_LIST3                       1599
#define IDC_LIST_FRIEND                 1599
#define IDC_LIST_OVERMEMBER             1599
#define IDC_BTN_COLOR3                  1600
#define IDC_CHK_BASE                    1600
#define IDC_BTN_BAN                     1601
#define IDC_IMG_KNIGHTMARK              1601
#define IDC_BTN_COLOR4                  1602
#define IDC_STA_OFFER                   1602
#define IDC_CHK_RESOURCE                1602
#define IDC_BTN_COLOR5                  1603
#define IDC_STA_KNIGHTNAME              1603
#define IDC_CHK_BILLBOARD               1603
#define IDC_BTN_COLOR6                  1604
#define IDC_STA_HEADNAME                1604
#define IDC_BTN_SYNMANAGER              1604
#define IDC_BTN_COLOR7                  1605
#define IDC_STA_KNIGHTNUM               1605
#define IDC_CHK_ENEMY                   1605
#define IDC_STA_TEAMHEAD1               1605
#define IDC_STA_SYNLEV                  1605
#define IDC_BTN_COLOR8                  1606
#define IDC_STA_KNIGHTLEV               1606
#define IDC_STA_TEAMHEAD2               1606
#define IDC_BTN_COLOR9                  1607
#define IDC_STA_KNIGHTFAMOR             1607
#define IDC_STA_TEAMHEAD3               1607
#define IDC_BTN_COLOR10                 1608
#define IDC_STA_KNIGHTMONEY             1608
#define IDC_STA_TEAMHEAD4               1608
#define IDC_BUTTON1                     1609
#define IDC_CHK_SEL1                    1609
#define IDC_CHK_HOTKEYF1                1609
#define IDC_BTN_ADDONE                  1609
#define IDC_SLIDER_SOUND                1609
#define IDC_BTN_DELSTUDENT              1609
#define IDC_BUTTON_CHANGESIZE           1609
#define IDC_TASK_ITEMGRID               1609
#define IDC_BTN_LISTCLOSE               1609
#define IDC_BTN_STONE1                  1609
#define IDC_IMG_ROLESEL                 1609
#define IDC_IMG_TASKITEM                1609
#define IDC_BTN_UPBOARD                 1609
#define IDC_BTN_STARTGAME               1609
#define IDC_BTN_BACK                    1609
#define IDC_IMG_NPCFACE                 1609
#define IDC_GRID_MONSTER                1609
#define IDC_IMG_MSGFLASH                1609
#define IDC_BTN_CLOSEBOOTH              1609
#define IDC_CHK_ROLE                    1609
#define IDC_BTN_CHANNELSET              1609
#define IDC_IMG_AUCTIONITEM             1609
#define IDC_AUCITEM_GRID                1609
#define IDC_IMG_AUCITEM                 1609
#define IDC_STA_HERONAME                1609
#define IDC_BUTTON2                     1610
#define IDC_CHK_SEL2                    1610
#define IDC_CHK_HOTKEYF2                1610
#define IDC_BTN_PPAGE                   1610
#define IDC_BTN_GIVE                    1610
#define IDC_SLIDER_MUSIC                1610
#define IDC_BTN_TASKOK                  1610
#define IDC_BTN_REQLEV                  1610
#define IDC_BTN_STONE2                  1610
#define IDC_IMG_FACESEL                 1610
#define IDC_BTN_UPOK                    1610
#define IDC_BTN_LEFTPAGE                1610
#define IDC_GRID_EGGS                   1610
#define IDC_BTN_OPENHATCH               1610
#define IDC_BTN_COLORSET                1610
#define IDC_BTN_BID                     1610
#define IDC_BTN_ADDOK                   1610
#define IDC_IMG_MONEYITEM               1610
#define IDC_BUTTON3                     1611
#define IDC_CHK_SEL3                    1611
#define IDC_CHK_HOTKEYF3                1611
#define IDC_BTN_NPAGE                   1611
#define IDC_BTN_TASKCANCEL              1611
#define IDC_BTN_TASKGETOK               1611
#define IDC_BTN_STONE3                  1611
#define IDC_IMG_FACE                    1611
#define IDC_BTN_UPCANCEL                1611
#define IDC_BTN_RIGHTPAGE               1611
#define IDC_IMG_SOULSTONE               1611
#define IDC_BTN_OPENDEPOT               1611
#define IDC_BTN_CHECKOK                 1611
#define IDC_CHK_SKILL                   1611
#define IDC_CHK_PUB                     1611
#define IDC_BTN_ADDCANCEL               1611
#define IDC_STA_HEROLEV                 1611
#define IDC_BUTTON4                     1612
#define IDC_CHK_SEL4                    1612
#define IDC_CHK_HOTKEYF4                1612
#define IDC_BTN_DELETE                  1612
#define IDC_BTN_TASKBACK                1612
#define IDC_BTN_SETKILLER               1612
#define IDC_BTN_CHGFACE                 1612
#define IDC_BTN_IMPROVE                 1612
#define IDC_CHK_TSKILL                  1612
#define IDC_CHK_SEC                     1612
#define IDC_STA_HEROTEAM                1612
#define IDC_BUTTON5                     1613
#define IDC_CHK_SEL5                    1613
#define IDC_CHK_HOTKEYF5                1613
#define IDC_BTN_TASKEXIT                1613
#define IDC_BTN_SETITEM                 1613
#define IDC_BTN_CHGBODY                 1613
#define IDC_BTN_ALIVEIMP                1613
#define IDC_BTN_ALIVE                   1613
#define IDC_CHK_BAN                     1613
#define IDC_BUTTON6                     1614
#define IDC_CHK_SEL6                    1614
#define IDC_CHK_HOTKEYF6                1614
#define IDC_BTN_SETMONSTER              1614
#define IDC_IMG_DATABK                  1614
#define IDC_BTN_BLACKNAME               1614
#define IDC_BUTTON7                     1615
#define IDC_CHK_SEL7                    1615
#define IDC_CHK_HOTKEYF7                1615
#define IDC_BTN_CLOSED                  1615
#define IDC_BTN_SETOK                   1615
#define IDC_BTN_CHATLOG                 1615
#define IDC_BUTTON8                     1616
#define IDC_CHK_SEL8                    1616
#define IDC_CHK_HOTKEYF8                1616
#define IDC_BTN_SETCANCEL               1616
#define IDC_BTN_SYNHEAD                 1616
#define IDC_BTN_ADDBLACKNAME            1616
#define IDC_BUTTON9                     1617
#define IDC_BTN_LISTUP                  1617
#define IDC_CHK_NONE                    1617
#define IDC_BTN_GROUP1                  1617
#define IDC_BTN_DELBLACKNAME            1617
#define IDC_BUTTON10                    1618
#define IDC_BTN_LISTDOWN                1618
#define IDC_BTN_LISDOWN                 1618
#define IDC_BTN_GROUP2                  1618
#define IDC_CHK_NAME1                   1618
#define IDC_BUTTON11                    1619
#define IDC_BTN_GROUP3                  1619
#define IDC_CHK_NAME2                   1619
#define IDC_LIST2                       1620
#define IDC_LIST_MEMBER                 1620
#define IDC_BTN_GROUP4                  1620
#define IDC_CHK_NAME3                   1620
#define IDC_BUTTON12                    1621
#define IDC_STA_PAGE                    1621
#define IDC_BTN_TEAM1                   1621
#define IDC_CHK_NAME4                   1621
#define IDC_BUTTON13                    1622
#define IDC_BTN_SEND                    1622
#define IDC_BTN_ORDER                   1622
#define IDC_BTN_TEAM2                   1622
#define IDC_CHK_NAME5                   1622
#define IDC_BUTTON14                    1623
#define IDC_BTN_PAGEUP                  1623
#define IDC_BTN_DOEDIT                  1623
#define IDC_BTN_TEAM3                   1623
#define IDC_CHK_NAME6                   1623
#define IDC_BUTTON15                    1624
#define IDC_BTB_PAGEDOWN                1624
#define IDC_BTN_OUT                     1624
#define IDC_BTN_PAGEDOWN                1624
#define IDC_BTN_TEAM4                   1624
#define IDC_BTN_GOTO                    1625
#define IDC_EDT_PAGENUM                 1626
#define IDC_CHK_MEMBER                  1627
#define IDC_CHK_LEVWORD                 1628
#define IDC_LIST_ENEMY                  1629
#define IDC_IMG_MARK                    1630
#define IDC_STA_NUMBER                  1631
#define IDC_STA_LEVEL                   1632
#define IDC_EDT_BILLBOARD               1633
#define IDC_BTN_PAGEGO                  1633
#define IDC_LIST_MEMBERS                1634
#define IDC_BTN_ADD                     1636
#define IDC_BTN_REGROUP                 1637
#define IDC_BTN_RENAME                  1638
#define IDC_BTN_GROUPRENAME             1638
#define IDC_BTN_ORDEROK                 1639
#define IDC_BTN_TEAMRENAME              1639
#define IDC_BTN_ORDERCANCEL             1640
#define IDC_STA_LISTSEL1                1641
#define IDC_STA_LISTSEL2                1642
#define IDC_BTN_LISTDOWN1               1643
#define IDC_BTN_LISTDOWN2               1644
#define IDC_BTN_MEMBERMOVE              1645
#define IDC_STA_SELTEAM1                1646
#define IDC_STA_SELTEAM2                1647
#define IDC_STA_SELTEAM3                1648
#define IDC_STA_SELTEAM4                1649
#define IDC_STA_SELTEAM5                1650
#define IDC_STA_OVERTEAM1               1651
#define IDC_STA_OVERTEAM2               1652
#define IDC_STA_OVERTEAM3               1653
#define IDC_STA_OVERTEAM4               1654
#define IDC_STA_OVERTEAM5               1655
#define IDC_LIST_SELMEMBER              1656
#define IDC_BTN_LEFTLISTUP              1657
#define IDC_BTN_LEFTLISTDOWN            1658
#define IDC_BTN_RIGHTLISTUP             1659
#define IDC_BTN_RIGHTLISTDOWN           1660
#define IDC_BTN_RENAMEOK                1662
#define IDC_BTN_RENAMECANCEL            1663
#define IDC_BTN_HIDEGOODS               1664
#define IDC_GRI_GOODBOX                 1665
#define IDC_SLIDER1                     1670
#define IDC_CHATSET_SLIDERUP            1671
#define IDC_STA_SERVER1                 1671
#define IDC_STA_SERVER2                 1672
#define IDC_STA_SERVER3                 1673
#define IDC_STA_SERVER4                 1674
#define IDC_STA_SERVER5                 1675
#define IDC_BTN_SERVER1                 1676
#define IDC_BTN_SERVER2                 1677
#define IDC_STA_MP                      1677
#define IDC_BTN_SERVER3                 1678
#define IDC_STA_MAGICNAME               1678
#define IDC_BTN_SERVER4                 1679
#define IDC_BTN_VIEWCHG                 1679
#define IDC_BTN_SERVER5                 1680
#define IDC_BTN_LEAVE                   1680
#define IDC_STATIC_TASKTITLE            1681
#define IDC_STATIC_REQLEV               1682
#define IDC_EDIT_TASKNAME               1682
#define IDC_STATIC_TASKINFO             1683
#define IDC_STA_REQLEV                  1683
#define IDC_STATIC_TASKMONEY            1684
#define IDC_STATIC_MAGICDEC             1684
#define IDC_STATIC_TASKREQINFO          1685
#define IDC_STA_SEX                     1685
#define IDC_BTN_LEFT1                   1686
#define IDC_BTN_UPPAGE                  1691
#define IDC_BTN_DOWNPAGE                1692
#define IDC_STA_TDEGREE                 1694
#define IDC_STA_INFO                    1695
#define IDC_BTN_CANCELBOARD             1696
#define IDC_STA_NPCINFO                 1698
#define IDC_STA_LEVEL1                  1699
#define IDC_STA_ATTACT1                 1700
#define IDC_STA_MAGICATTACT1            1701
#define IDC_STA_LEVEL2                  1702
#define IDC_STA_ATTACT2                 1703
#define IDC_STATIC_MSG                  1703
#define IDC_STA_MAGICATTACT2            1704
#define IDC_DEPOT_FACTION               1704
#define IDC_STA_LEVEL3                  1705
#define IDC_DEPOT_NAME                  1705
#define IDC_STA_ATTACT3                 1706
#define IDC_STATIC_TXTACTION            1706
#define IDC_STA_MAGICATTACT3            1707
#define IDC_STATIC_VALUE                1707
#define IDC_STA_LEVEL4                  1708
#define IDC_STA_IDENTMONEY              1708
#define IDC_STA_ATTACT4                 1709
#define IDC_STA_MAGICATTACT4            1710
#define IDC_STA_LEVEL5                  1711
#define IDC_STA_ATTACT5                 1712
#define IDC_STA_MAGICATTACT5            1713
#define IDC_MONSTER1                    1714
#define IDC_BTN_ADDMEMBER               1715
#define IDC_BTN_KICKOUT                 1716
#define IDC_BTN_SETJOB                  1717
#define IDC_BTN_LEADERNEXT              1717
#define IDC_BTN_DOC                     1718
#define IDC_STA_SYNHEAD                 1720
#define IDC_STA_WRITER                  1720
#define IDC_STA_SYNFHEAD                1721
#define IDC_STA_TIME                    1721
#define IDC_STA_DOC1                    1723
#define IDC_STA_DOC2                    1724
#define IDC_STA_DOC3                    1725
#define IDC_STA_DOC4                    1726
#define IDC_STA_DOC5                    1727
#define IDC_STA_DOC6                    1728
#define IDC_STA_DOC7                    1729
#define IDC_STA_PAGEAMOUNT              1730
#define IDC_IMG_OK1                     1731
#define IDC_IMG_OK2                     1732
#define IDC_IMG_OK3                     1733
#define IDC_IMG_OK4                     1734
#define IDC_IMG_OK5                     1735
#define IDC_IMG_OK6                     1736
#define IDC_IMG_OK7                     1737
#define IDC_IMG_NOTOK1                  1738
#define IDC_IMG_NOTOK2                  1739
#define IDC_CHK_TEAMSEL1                1739
#define IDC_IMG_NOTOK3                  1740
#define IDC_CHK_TEAMSEL2                1740
#define IDC_IMG_NOTOK4                  1741
#define IDC_CHK_TEAMSEL3                1741
#define IDC_IMG_NOTOK5                  1742
#define IDC_CHK_TEAMSEL4                1742
#define IDC_IMG_NOTOK6                  1743
#define IDC_CHK_TEAMOVER1               1743
#define IDC_IMG_NOTOK7                  1744
#define IDC_CHK_TEAMOVER2               1744
#define IDC_BTN_ADDFRIEND               1744
#define IDC_CHK_ENEMYLIST               1744
#define IDC_CHK_TEAMOVER3               1745
#define IDC_BTN_ADDENEMY                1745
#define IDC_BTN_BILLBOARD               1745
#define IDC_STA_DOC8                    1745
#define IDC_CHK_TEAMOVER4               1746
#define IDC_BTN_DELENEMY                1746
#define IDC_IMG_OK8                     1746
#define IDC_BTN_DELFRIEND               1747
#define IDC_IMG_NOTOK8                  1747
#define IDC_CHK_FRIENDLIST              1747
#define IDC_CHK_GOODS                   1754
#define IDC_CHK_STONES                  1755
#define IDC_STA_MEMBERNAME              1756
#define IDC_STA_IMG1                    1757
#define IDC_STA_IMG2                    1758
#define IDC_STA_IMG3                    1759
#define IDC_CHK_ORDAIN1                 1760
#define IDC_CHK_ORDAIN2                 1761
#define IDC_CHK_ORDAIN3                 1762
#define IDC_GROUP_MENUA1                1763
#define IDC_GROUP_MENUA2                1764
#define IDC_STA_EDITBKIMG               1764
#define IDC_GROUP_MENUA3                1765
#define IDC_GROUP_MENUA4                1766
#define IDC_STAT_OLDNAME                1766
#define IDC_GROUP_MENUB1                1767
#define IDC_IMG_SKILL1                  1767
#define IDC_GROUP_MENUB2                1768
#define IDC_IMG_SKILL2                  1768
#define IDC_GROUP_MENUB3                1769
#define IDC_IMG_SKILL3                  1769
#define IDC_GROUP_MENUB4                1770
#define IDC_IMG_SKILL4                  1770
#define IDC_GROUP_MENUA5                1771
#define IDC_STA_DESCM1                  1771
#define IDC_GROUP_MENUB5                1772
#define IDC_IMG_HEADBACK1               1773
#define IDC_BTN_CALL1                   1774
#define IDC_BTN_ATTACH1                 1775
#define IDC_BTN_CALL2                   1776
#define IDC_BTN_ATKSTATUS1              1776
#define IDC_BTN_ATTACH2                 1777
#define IDC_BTN_ATKSTATUS2              1777
#define IDC_IMG_HEADBACK2               1778
#define IDC_BTN_ATKSTATUS3              1778
#define IDC_BTN_CALL3                   1779
#define IDC_BTN_ATKSTATUS4              1779
#define IDC_BTN_ATTACH3                 1780
#define IDC_IMG_HEADBACK3               1781
#define IDC_BTN_CALL4                   1782
#define IDC_BTN_ATTACH4                 1783
#define IDC_IMG_HEADBACK4               1784
#define IDC_STA_HP1                     1785
#define IDC_STA_HP2                     1786
#define IDC_BTN_PAGELEFT                1786
#define IDC_STA_HP3                     1787
#define IDC_BTN_PAGERIGHT               1787
#define IDC_MONSTEREVOLVE_STA_NAME      1787
#define IDC_STA_HP4                     1788
#define IDC_IMG_BEFOREEVOLVED           1788
#define IDC_STA_XP1                     1789
#define IDC_IMG_AFTEREVOLVE             1789
#define IDC_STA_XP2                     1790
#define IDC_BTN_EVOLVE                  1790
#define IDC_STA_XP3                     1791
#define IDC_STATE_IMAFACE               1791
#define IDC_STA_XP4                     1792
#define IDC_STA_PROSITION               1792
#define IDC_STA_SYNJOB                  1793
#define IDC_BTN_GIVEOK                  1795
#define IDC_BTN_GIVECANCEL              1796
#define IDC_ROOMLG_BTN_RETURN           1797
#define IDC_IMG_BADSTATUS               1798
#define IDC_EDIT_NAME                   1799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        369
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1800
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
