
//**********************************************************\\
// 代码编辑器\\
//**********************************************************\\
\\
#ifndef CN_RES_H
#define CN_RES_H
//---------------------------------------------------------------------------

#define	STR_BEKILL_ss				"%s 学艺不精，惨死在 %s 手下!"
#define	STR_MISS_BET				"错失良机，请留意下次..."
#define	STR_SETLOCK					"setlock"
#define	STR_UNLOCK					"unlock"
#define	STR_CLEARLOCK				"clearlock"
#define	STR_SETLOCK_HELP			"设置保护锁错误! 设新密码之前请先清除旧密码,不能使用过于简单的密码，密码必须为六至九位整数，也不能使用字母或符号。使用方法：/setlock 密码"
#define	STR_UNLOCK_HELP				"输入密码错误! 临时打开“保护锁”，请使用“/unlock 密码”"
#define	STR_CLEARLOCK_HELP			"输入密码错误! 永久清除“保护锁”，请使用“/clearlock 旧密码”"
#define	STR_SETLOCK_OK				"已设置“保护锁”的密码。可使用“/unlock 密码”临时打开保护锁，也可使用“/clearlock 旧密码”永久清除保护锁。"
#define	STR_SETLOCK_FAIL			"设置“保护锁”失败! 设新密码之前请先清除旧密码,不能使用过于简单的密码，密码必须为六至九位整数，也不能使用字母或符号。"
#define	STR_UNLOCK_OK				"已打开“保护锁”，下线后会自动加锁。"
#define	STR_CLEARLOCK_OK			"已永久清除“保护锁”，该帐号不再受到“保护锁”的保护。如需重新设置保护锁，请使用“/setlock 密码”。"
#define	STR_LOCKKEY_DENY			"请先打开“保护锁”。使用方法：/unlock 密码"
#define	STR_NO_LOCKKEY				"暂未设置密码。"
#define	STR_UPLEV_HOLE1				"%s吉星高照，%s升级时冲出第一个宝石孔！"
#define	STR_UPLEV_HOLE2				"%s吉星高照，%s升级时冲出第二个宝石孔！"
#define	STR_WIN_BET_sd				"%s红光满面，双眉带彩，玩骰子赢了%d两！"
#define	STR_AWARD_VIRTUE_su			"%s得到功德值%u。"
#define	STR_SYNDICATE_LEADER		"帮主"
#define	STR_SYNDICATE_LEADER2		"副帮主"
#define	STR_SYNDICATE_LEADER3		"堂主"
#define	STR_SYNDICATE_LEADER4		"副堂主"
#define	STR_SYNDICATE_LEADER5		"代堂主"
#define	STR_SYNDICATE_MEMBER		"帮众"
#define	STR_ERROR					"错误"
#define	STR_DELETE_FAILED			"删除失败!"
#define	STR_YOUR_CANNOT_WALK		"您不能走！"
#define	STR_TOP_LIST_dsd			"第%d名：%s(%d)"
#define	STR_KICKOUT_ALL_AFTER		"开始处理kickoutall，服务器禁止登录。%d秒之后，所有玩家退出。"
#define	STR_KICKOUT_ALL				"开始处理kickoutall，服务器禁止登录，所有玩家退出中 . . ."
#define	STR_LOGIN_ANOTHER			"有人正在登陆此帐号。"
#define	STR_LOGIN_AGAIN				"此帐号已经有人登陆。"
#define	STR_WEAPON_SKILL_UPLEV		"恭喜阁下武器熟练度又升一级。"
#define	STR_KO_LIST_TITLE			"名次  姓名           数量"
#define	STR_TEAM_MONEY_s			"捡钱开关 %s"
#define	STR_TEAM_ITEM_s				"捡物品开关 %s"
#define	STR_OPEN					"开"
#define	STR_CLOSE					"关"
#define STR_NOT_DISCARDABLE			"此物品不能丢弃或出售。"
#define STR_NEXT_PAGE				"下一页"
#define STR_CLOSE_BUTTON			"关闭"
#define STR_TOO_LOWER_SYN_MONEY		"帮派基金不足，该功能已关闭。"
#define STR_HITRATE_ADD				"技能启动：%d秒内命中率增加到%d％。"
#define STR_DEFENCE_ADD				"技能启动：%d秒内防御力增加%d倍。"
#define STR_DEFENCE_ADD2			"技能启动：%d秒内防御力增加%d％。"
#define STR_ATTACK_ADD				"技能启动：%d秒内攻击力增加到%d％。"
#define STR_DODGE_ADD				"技能启动：%d秒内躲避率增加到%d％。"
#define DRAGON_BALL_DROP			"宝光一闪，%s从怪物身上打出一个龙珠。"
#define EXPLOST_PAYBY_SYNFUND		"帮派基金抵消经验损失%u。"
#define MALE_MATE_LOGIN				"老公来了，赶紧去查勤。"
#define FEMALE_MATE_LOGIN			"老婆大人来了，赶紧去请安吧。"
#define NOMATE_NAME					"无"
#define TITILE_NONE					"无"
#define SYNNAME_NONE				"无"
#define	ACTIONSTR_NONE				"无"
#define	STR_DESTROY_SYNDICATE_SOON	"贵帮因帮派基金耗尽，即将被系统强行解散。请及时补充帮派基金。"
#define	STR_TARGET_OFFLINE			"对方不在线。"
#define	STR_SUPERMAN_BROADCAST_sddd	"%s 武艺精湛，在爆发时间内杀死%d只怪物，荣登KO排行榜的第%d名，奖励KO时间%d秒。"
#define	STR_SYNDICATE_COMBINESUB_ss	"帮派 %s 被 % 吞并了。"
#define	STR_NEXTEQP_OVERLEV			"下一个等级的装备已经超出阁下当前等级！"
#define	STR_DISPATCHXP_s			"%s 一声怒吼，同队的战友个个精神一震，XP值上升！"
#define	STR_BOOTH_BUY_sds			"%s 花了 %d 两购买你的%s。"
#define	STR_DISABLE_LAY_SYNTRANS	"该地图禁止放置此类NPC!"
#define	STR_ITEM_LEV_TOO_HIGH		"装备需求等级太高!"
#define	STR_TEAM_HUNT				"%s做恶多端，终于被以%s为首的缉捕队伍抓获!"
#define	STR_FOND_WANTED				"发现悬赏目标【%s】！"
#define	STR_FOND_POLICEWANTED		"发现官府悬赏目标【%s】！"
#define	STR_CANT_STORAGE			"该物品不能存放!"
#define	STR_SYN_FULL				"错误：帮派人数已满!"
#define	STR_JOIN_SYN_FAILED			"错误：加入失败!"
#define	STR_INVALID_PET_NAME		"错误：不允许的名字!"
#define	STR_KICKOUT_MEMBER_s		"%s屡违帮规，为严肃帮务，将其永远逐出本帮，以儆效尤。"
#define	STR_KICKOUT_ME_s			"你被%s从帮派中开除。"
#define	STR_NO_ENOUGH_POWER			"阁下的内力不足，不能千里传音!"
#define	STR_NO_ENOUGH_LEVEL			"阁下的修行太低，不能千里传音!"
#define	STR_NO_BONUS				"抱歉，没有奖品或者奖品 或 没有经过领奖网页确认。"
#define	STR_WARNING_CRASH			"注意：此命令只用于本地测试，否则可能导致服务器崩溃!"
#define	STR_CAN_STAND				"目标点不能落脚!"
#define	STR_SET_MAX_PLAYERS_u		"最大允许登录人数改为: %u"
#define	STR_SHOW_PLAYERS_uu			"当前在线:%u, 最大在线:%u"
#define	STR_CAN_NOT_TALK			"您被点穴了，无法说话!"
#define	STR_ARRESTMENT_PK_MODE		"捕杀PK模式，你可以攻击怪物和黑名、蓝名玩家，不会伤害到其它人。"
#define	STR_TEAM_PK_MODE			"组队PK模式，你可以攻击怪物和其它人，不会伤害到自己和队友。"
#define	STR_SAFE_PK_MODE			"安全PK模式，你只能攻击怪物，不会伤害到其它任何玩家。"
#define	STR_FREE_PK_MODE			"自由PK模式，你可以攻击任何人。"
#define	STR_NEED_PICK				"必须要装备鹤嘴锄才能挖矿。"
#define	STR_SYNDICATE_DESTROY_s		"帮派 %s 解散了。"
#define	STR_SYNDICATE_CREATE_ss		"恭喜 %s 创建%s成功。 "
#define	STR_SYN_LEADER_LOSE_uss		"帮派[%u][%s]帮主失踪，玩家[%s]顶替帮主。"
#define	STR_DONATE_ssd				"%s 向%s捐款%d两银子。"
#define	STR_SYN_WAR_END				"帮派战结束!"
#define	STR_SYN_WAR_START			"帮派战开始!"
#define	STR_GOT_WIN_s				"%s获得胜利!"
#define	STR_ERROR_DUPLICATE_NAME	"错误：人物已存在!"
#define	STR_ERROR_ILLEGAL_NAME		"错误：角色名不合法!"
#define	STR_ERROR_ILLEGAL_PASSWORD	"错误：密码不合法!"
#define	STR_ERROR_ILLEGAL_ACCOUNT	"错误：帐号名不合法!"
#define	STR_ERROR_SERVER_FULL		"错误：服务器人数已满，请稍后重新登录!"
#define	STR_ERROR_LOWER_VERSION		"错误：版本号错误，请更新客户端!"
#define	STR_ERROR_VERSION			"错误：版本号错误!"
#define	STR_FEW_FEE_NOTIFY			"您的包月卡将于 %s 到期，请及时充值。"
#define	STR_ACCOUNT_NOFEE			"您的帐号还没有充值。"
#define	STR_LOGIN_ISP_FAIL			"登录到ISP计费系统失败。目前正在使用您自己的帐号进行计费。"
#define	STR_FEETYPE_KNOWN			"计费类型：未知。"
#define	STR_FEETYPE_HOUR			"计费类型：小时卡，剩余小时数：%d.%d。"
#define	STR_FEETYPE_MONTH			"计费类型：包月卡。到期时间：%d年%d月%d日。"
#define	STR_FEETYPE_BARHOUR			"计费类型：网吧计点。"
#define	STR_FEETYPE_BARMONTH		"计费类型：网吧月卡。许可证数量%d。"
#define	STR_FEETYPE_ISP				"计费类型：ISP计费。"
#define	STR_FEETYPE_FREE			"计费类型：免费测试。"
#define	STR_SHUTDOWN_NOTIFY			"服务器维护，停机三十分钟；请大家立即下线，避免数据丢失。"
#define	STR_NONSUCH_TRADE_sssu		"[交易] 极品交易，玩家[%s]给玩家[%s]物品[%s][%u]"
#define	STR_NOT_SO_MUCH_MONEY	    "阁下没有这么多钱。"
#define	STR_NOT_ENOUGH_MONEY	    "你的钱不足%d两!"
#define	STR_DIE_FORGIVE	            "人死如灯灭，何苦纠缠不休？"
#define	STR_DIE_STOP_ATTACK	        "死者为大，禁止鞭尸。"
#define	STR_ATTACK_POLICE	        "阁下涉嫌袭警，请好自为之，以免惹火上身。"
#define	STR_KILLING_EXPERIENCE	    "获击杀额外经验%u。"
#define	STR_KILLING_EXPEX			"获低等级队友奖励和击杀额外经验%u。"
#define	STR_BAG_FULL	            "背包已满!"
#define	STR_TRADE_SUCCEED	        "交易成功。"
#define	STR_TRADE_FAIL	            "交易失败!"
#define	STR_USE_ITEM	            "您用掉了一件物品。"
#define	STR_INVALID_GUILD_NAME		"帮派名字不合法!"
#define	STR_GUILD_FUND_NOT_ENOUGH	"帮派基金不足%u两!"
#define	STR_NOT_AUTHORIZED	        "你没有这个权力!"
#define	STR_ALLY_FULL	            "结盟表已满!"
#define	STR_SYN_PLACE_FULL	        "职位数量已满!"
#define	STR_WANTED_ORDER	        "扣除定金%u两，取得%d号悬赏单，目标：%s，赏金：%u 两。"
#define	STR_WANTED_INFO				"据传此人最近在【%s】一带活动。"
#define	STR_INVALID_WANTED	        "错误的悬赏号！"
#define	STR_MAX_BONUTY				"赏金最大不能超过%d两！"
#define	STR_MIN_BONUTY				"赏金最少不能低于%d两！"
#define	STR_SUPERADD_BONUTY			"悬赏%u号赏金上升为%u两！"
#define	STR_LOWEST_SUPERADD_BONUTY	"最低添加悬赏额为%u两！"
#define	STR_CANCEL_WANTED			"悬赏%u号已经撤销。"
#define	STR_NO_DISBAND	            "帮派较大不宜解散，请选择禅让。"
#define	STR_PROTECTED_CODE	        "请先打开保护锁。"
#define	STR_HIS_ALLY_FULL	        "对方的结盟表已满!"
#define	STR_NOT_HERE	            "该玩家不在附近!"
#define	STR_NOT_ENOUGH_LEV			"你的等级不足%d级!"
#define	STR_LEVEL_NOT_ENOUGH	    "对方等级不够!"
#define	STR_INVALID_NAME	        "名字不合法。"
#define	STR_INVALID_MSG	            "非法消息！"
#define	STR_MAGIC_FAILED            "法术失败！"
#define	STR_CANNOT_DEPOSIT	        "错误：此物品不宜存放!"
#define	STR_FORBIDDEN_GUILD_NAME	"您不能使用这个帮派名。"
#define	STR_GUILD_INEXIST	        "该帮派不存在。"
#define	STR_TEAM_EXPERIENCE	        "获得了组队奖励经验%d"
#define	STR_TEAM_EXPEX				"获得组队和低等级队友奖励经验%d"
#define	STR_LOST_EXPERIENCE	        "你损失了%d点经验值!"
#define	STR_KILLING_TO_MUCH	        "杀人过多，有违天和，小心报应！"
#define	STR_NOT_PK_MODE	            "当前模式下不能攻击对方！"
#define	STR_NOT_PK_EXP	            "经验为负的情况下不能PK。"
#define	STR_PK_FORBIDDEN	        "此处禁止殴斗。"
#define	STR_MSG_SENT	   		    "留言成功，对方上线后就能看到你的留言。"
#define	STR_MSG_FAILED				"每个好友留言间隔不能少于%d分钟，留言失败。"
#define	STR_INVALID_COORDINATE	    "非法坐标。"
#define	STR_GONE	                "走了"
#define	STR_JUMPED	                "跳了"
#define	STR_CONNECTION_OFF	        "客户端网络连接异常，系统自动关闭连接。"
#define	STR_WEAPON_SKILL_UP	        "恭喜阁下武器熟练度升级！"
#define	STR_TEAMMATE_CANNOT_CREATE	"[队伍]您已经在队伍中了，不能创建新队伍。"
#define	STR_CREATE_TEAM_FAILED	    "[队伍]您创建队伍失败。"
#define	STR_FULLBAG_NO_MORE	        "阁下行囊已满，无法放入更多物品。"
#define	STR_HEAVEY_BAG	            "阁下行囊过重，无法放入更多物品。"
#define	STR_ITEM_NOT_FOUND	        "物品找不到!"
#define	STR_ITEM_INEXIST	        "物品不存在!"
#define	STR_MONEYBAG_FULL	        "您的钱袋已满!"
#define	STR_MAKE_ITEM_FAILED        "产生地图物品[%u]失败。"
#define	STR_MAKE_MONEY_FAILED	    "产生地图银两[%d]失败。"
#define	STR_DAMAGED_REPAIR	        "%s即将损坏，请尽快修复，否则将彻底消失!"
#define	STR_DURABILITY_REPAIR	    "%s耐久度太低，请尽快修复，以免损伤。"
#define	STR_FAR_CANNOT_PICK	        "物品太远，无法拾取。"
#define	STR_FULL_CANNOT_PICK	    "物品栏已满，无法拾取物品。"
#define	STR_PICK_MONEY	            "捡到银子 %u 两。"
#define	STR_FAILED_GENERATE_ITEM	"产生物品失败。"
#define	STR_OTHERS_ITEM	            "别人的打的东西，暂时不能拾取!"
#define	STR_GOT_ITEM	            "得到物品%s。"
#define	STR_DRAGONBALL	            "改良装备辅助物品必须是【龙珠】。"
#define	STR_REPAIR_THEN_IMPROVE	    "改良装备必须是修复好的物品。"
#define	STR_SUPERIOR_ALREADY	    "此装备已经是极品了。"
#define	STR_CONNOT_IMPROVE	        "该装备无法改良。"
#define	STR_METEOR	                "升级装备的辅助物品必须是【流星】。"
#define	STR_REPAIR_THEN_UPGRADE	    "升级装备必须是修复好的物品。"
#define	STR_UPGRADE_NOMORE	        "此装备无法继续升级！"
#define	STR_MINE_WITH_PECKER   	    "必须要装备鹤嘴锄才能挖矿。"
#define	STR_NO_MINE	                "此地没有矿藏。"
#define	STR_GOLD_ORE	            "得到一个金矿石！"
#define	STR_EUXENITE_ORE	        "得到一个黑铁矿！"
#define	STR_IRON_ORE	            "得到一个铁矿石！"
#define	STR_COPPER_ORE	            "得到一个铜矿石！"
#define	STR_SILVER_ORE	            "得到一个银矿石！"
#define	STR_GAIN_GEM	            "恭喜获得一颗宝石！"
#define	STR_UNQUALIFIED	            "错误：条件检查失败！"
#define	STR_DIE	                    "您已经死了!"
#define	STR_DONOT_GIVE_UP	        "阁下身负重任，怎可自暴自弃？"
#define	STR_NO_MANA_UNLOCK		    "内力不足，不能冲穴!"
#define	STR_NO_CULTIVATION		    "阁下修为太浅，冲穴失败!"
#define	STR_CANNOT_JUMP	            "您不能跳！"
#define	STR_CHEAT	                "[作弊]你要分配的点数大于拥有的可分配点数。"
#define	STR_FRIEND_LIST_FULL	    "好友列表已满。"
#define	STR_YOUR_FRIEND_ALREADY	    "对方已经是好友了。"
#define	STR_MAKE_FRIEND_SENT        "已经发送结拜请求。"
#define	STR_NOT_YOUR_FRIEND	        "%s 不是你的朋友。"
#define	STR_NO_PK_VILLAGE	        "新手村禁止PK！"
#define	STR_NEVER_PROPOSED	        "阁下自作多情了点吧？%s 没有向你求过婚。"
#define	STR_SINGLE	                "阁下尚未婚配，何故要做纷飞劳燕？"
#define	STR_NOT_YOUR_SPOUSE	        "看清楚咯，%s 和阁下并非夫妻关系啊。"
#define	STR_NOT_ENOUGH_MANA	        "您的内力不足。"
#define	STR_UNABLE_USE_ITEM	        "无法使用物品!"
#define	STR_YOUR_BAG_FULL	        "物品栏已满!"
#define	STR_SELFCARE			    "自顾身份。"
#define	STR_CAUTION					"小心为妙。"
#define	STR_BALANCED			    "势均力敌。"
#define	STR_INVALID_AMOUNT	        "数量错误!"
#define	STR_REPAIR_FAILED	        "修理不成功!"
#define	STR_INVALID_TITLE	        "错误：封号名不合法!"
#define	STR_NOT_FROM_YOUR_GUILD	    "对方不是阁下帮派的弟子。"
#define	STR_ITEM_DAMAGED	        "该物品损坏了!"
#define	STR_VITAL_POINT_STRICKEN	"您被点穴了，无法说话!"
#define	STR_CHANGE_NAME	            "阁下已经更名为%s。"
#define	STR_INCREASE_MONEY	        "[您的钱增加了。]"
#define	STR_INCREASE_ITEM	        "[您的物品增加了。]"
#define	STR_KICKOUTALL	            "开始处理kickoutall，服务器禁止登录，所有玩家退出中 . . ."
#define	STR_ACTION_SEEN	            "可以显示ACTION了。"
#define	STR_ACTION_NOTSEEN	        "不显示ACTION了。"
#define	STR_NO_STOP	                "目标点不能落脚!"
#define	STR_LOCAL_TEST	            "注意：此命令只用于本地测试，否则可能导致服务器崩溃!"
#define	STR_ACTION_UPDATED	        "[ACTION 更新了。]"
#define	STR_KICK_OUT_GUILD	        "%s 已经被开除出帮派！"
#define	STR_NO_PRIZE	            "抱歉，没有奖品或者奖品 或 没有经过领奖网页确认。"
#define	STR_NO_LV_BROADCAST	        "阁下的修行太低，不能千里传音!"
#define	STR_NO_MANA_BROADCAST	    "阁下的内力不足，不能千里传音!"
#define	STR_INVALID_CHARACTER	    "消息中包含非法字符!"
#define	STR_LOW_LEVEL	            "你的等级太低!"
#define	STR_GM_NO_TEAM	            "【GM】不能进行队伍操作。"
#define	STR_INTEAM_NOJOIN		    "[队伍]您已经有队伍了。不能申请加入新队伍。"
#define	STR_NO_APPLICANT		    "[队伍]没有找到申请对象。"
#define	STR_NO_TEAM					"[队伍]对方还没有组队。"
#define	STR_FORBIDDEN_JOIN	        "[队伍]对方队伍禁止加入了。"
#define	STR_TEAM_FULL			    "[队伍]对方队伍已经满了。"
#define	STR_NO_CAPTAIN_CLOSE	    "[队伍]请直接向队长提出申请。"
#define	STR_JOIN_REQUEST_SENT	    "[队伍]已经发出加入队伍请求。"
#define	STR_INVI_SENT			    "[队伍]加入队伍申请已经提交，请等待回应。"
#define	STR_NO_TEAM_TO_INVITE	    "[队伍]您没有队伍，怎能接受别人加入队伍？"
#define	STR_NOT_CAPTAIN_INVITE	    "[队伍]您不是队长，怎能接受别人加入队伍？"
#define	STR_YOUR_TEAM_FULL		    "[队伍]您的队伍已经满员了。"
#define	STR_APPLICANT_NOT_FOUND	    "[队伍]没有找到发出申请的玩家。"
#define	STR_HAVE_JOIN_TEAM	        "[队伍]您已经加入队伍了，不能同时加入另外一个。"
#define	STR_NOT_TO_JOIN	            "[队伍]对方没有发出加入申请，您不能接受对方。"
#define	STR_NOTEAM_TO_INVITE	    "[队伍]您没有队伍，怎能邀请别人加入队伍？"
#define	STR_TEAM_CLOSED	            "[队伍]您已经关闭队伍了，请先打开队伍。"
#define	STR_NOT_CAPTAIN_ACCEPT	    "[队伍]您不是队长，怎能邀请别人加入队伍？"
#define	STR_INVITED_NOT_FOUND	    "[队伍]没有找到要邀请的玩家。"
#define	STR_HAS_IN_TEAM	            "[队伍]对方已经有队伍了，邀请失败。"
#define	STR_INVITE_SENT				"[队伍]已经发出邀请加入队伍请求。"
#define	STR_SENT_WAIT				"[队伍]邀请已经发出，请等待。"
#define	STR_INTEAM_NOACCEPT			"[队伍]您已经是队员了，不能接受邀请加入新队伍。"
#define	STR_INVITER_NOT_FOUND	    "[队伍]没有找到邀请者。"
#define	STR_NOT_CREATE_TEAM		    "[队伍]对方还没有组队。"
#define	STR_HIS_TEAM_FULL		    "[队伍]对方的队伍已经满员了。"
#define	STR_NOT_BE_INVIITED	  	    "[队伍]对方没有向您发出加入队伍的邀请，操作失败。"
#define	STR_NO_TEAM_TO_LEAVE	    "[队伍]您还不是队员，不能退出队伍。"
#define	STR_NO_TEAM_TO_DISMISS	    "[队伍]您还没有队伍，不能解散队伍。"
#define	STR_NOT_CAPTAIN_DISMISS	    "[队伍]您不是队长，不能解散队伍。"
#define	STR_NO_TRADE_IN_BATTLE	    "错误：战斗中不能执行交易指令！"
#define	STR_NO_TRADE_IN_TEAM	    "错误：组队状态不能执行交易指令！"
#define	STR_NO_IN_TEAM				"[队伍]您没有队伍。"
#define	STR_NO_TRADE_TARGET	        "[交易]没有找到交易对象。"
#define	STR_TARGET_TRADING	        "[交易]对方正在交易中，请稍后再试!"
#define	STR_TRADING_REQEST_SENT	    "[交易]已经发出交易请求。"
#define	STR_NOT_FOR_TRADE	        "错误：不能交易此物品!"
#define	STR_CANNOT_GO				"您不能走！"
#define	STR_FREE_PK	                "自由PK模式，你可以攻击任何人。"
#define	STR_PEACE	                "安全PK模式，你只能攻击怪物，不会伤害到其它任何玩家。"
#define	STR_TEAM_PK	                "组队PK模式，你可以攻击怪物和其它人，不会伤害到自己和队友。"
#define	STR_JOIN_A_GUILD	        "%s 加入了帮派。"
#define	STR_BONUS					"恭喜获得%u个奖品，请去交易市场领奖处领奖！"
#define	STR_TO_MAKE_FRIEND			"江湖虽大，知音难觅，%s深感友情之可贵，欲效古人，与你共结金兰之好！"
#define	STR_MAKE_FRIEND				"%s 与 %s 歃血为盟，义结金兰，从此有福同享，有难同当！"
#define	STR_BREAK_FRIEND			"%s 羞于与 %s 为伍，于是割袍断义，从此不再往来。"
#define	STR_MARRY					"执子之手，与子偕老。%s 和 %s 立下永不分离的誓言，结成秦晋之好。"
#define	STR_DIVORCE					"%s 和 %s 感情破裂，宣布离婚！"
#define	STR_SYN_CONQUER				"【%s】经过浴血奋战，终于夺得帮派总坛!"
#define	STR_POLICE_WANTED_ORDER		"揭榜确认：追捕目标%s，据传此人最近在%s一带出没。"
#define	STR_GOTO_JAIL				"%s 杀人如麻，终于失手被擒，打入大牢。"

//---------------------------------------------------------------------------
#endif
